site_name: 'Agenttiharnessin kehittämisen oppimispäiväkirja'
site_url: !ENV [CI_PAGES_URL, ""]
site_description: 'KAMK:n kurssiprojektin oppimispäiväkirja'

theme:
  name: 'material'
  language: 'fi'
  palette:
    primary: 'blue grey'

markdown_extensions:
  # Footnotes
  - footnotes
  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # Emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Checkboxes
  - pymdownx.tasklist:
      custom_checkbox: true
  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence.fence_mermaid

plugins:
  # Navigation page ordering
  - awesome-nav
  - search
  - mermaid2

extra:
  generator: false
