[project]
name = "oppimispaivakirja-agenttiharness"
version = "0.42.0"
description = "KAMK:n kurssiprojektin oppimispäiväkirja."
readme = "README.md"
requires-python = ">=3.12,<4.0"

authors = [
    { name = "Eemeli Kuittinen" }
]

dependencies = [
    "mkdocs-material",
    "mkdocs-awesome-nav",
    "mkdocs-mermaid2-plugin"
]
