use crate::UnwrapOrAbort;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use tempfile::TempDir;

use crate::fakes::FakeIdSource;

const DEFAULT_SEED: u64 = 42;

#[derive(Debug)]
pub struct TestWorkspace {
    root: TempDir,
    seed: u64,
    clock: TestClock,
    ids: FakeIdSource,
}

impl TestWorkspace {
    pub fn new() -> io::Result<Self> {
        Self::with_seed(DEFAULT_SEED)
    }

    pub fn with_seed(seed: u64) -> io::Result<Self> {
        let root = tempfile::Builder::new()
            .prefix("harness-test-workspace-")
            .tempdir()?;
        let workspace = Self {
            root,
            seed,
            clock: TestClock::default(),
            ids: FakeIdSource::new(seed),
        };
        workspace.create_standard_dirs()?;
        workspace.write_default_config()?;
        Ok(workspace)
    }

    pub fn root(&self) -> &Path {
        self.root.path()
    }

    pub fn config_path(&self) -> PathBuf {
        self.root().join("harness.jsonc")
    }

    pub fn sessions_dir(&self) -> PathBuf {
        self.root().join("sessions")
    }

    pub fn artifacts_dir(&self) -> PathBuf {
        self.root().join("artifacts")
    }

    pub fn fixtures_dir(&self) -> PathBuf {
        self.root().join("fixtures")
    }

    pub fn seed(&self) -> u64 {
        self.seed
    }

    pub fn clock(&self) -> &TestClock {
        &self.clock
    }

    pub fn ids(&self) -> &FakeIdSource {
        &self.ids
    }

    pub fn path(&self, relative: impl AsRef<Path>) -> PathBuf {
        self.root().join(relative)
    }

    pub fn create_standard_dirs(&self) -> io::Result<()> {
        fs::create_dir_all(self.sessions_dir())?;
        fs::create_dir_all(self.artifacts_dir())?;
        fs::create_dir_all(self.fixtures_dir())?;
        Ok(())
    }

    pub fn write_default_config(&self) -> io::Result<()> {
        fs::write(self.config_path(), self.default_config_jsonc())
    }

    pub fn default_config_jsonc(&self) -> String {
        format!(
            r#"{{
  // Generated by harness-testkit::TestWorkspace.
  "runtime": {{
    "deterministic": {{
      "enabled": true,
      "seed": {seed}
    }},
    "session_dir": "{sessions}"
  }},
  "provider": {{
    "default": {{
      "type": "openai_compatible",
      "options": {{
        "baseURL": "http://127.0.0.1:8317/v1",
        "apiKey": "test-key"
      }},
      "models": {{
        "mock-model": {{
          "name": "Mock Model"
        }}
      }}
    }}
  }},
  "model": "default/mock-model",
  "agent": {{
    "default": {{
      "model": "default/mock-model",
      "tools": ["read"]
    }}
  }},
  "permission": "allow"
}}
"#,
            seed = self.seed,
            sessions = json_path(&self.sessions_dir()),
        )
    }
}

#[derive(Debug, Default)]
pub struct TestClock {
    mono_ms: AtomicU64,
}

impl TestClock {
    pub fn mono_ms(&self) -> u64 {
        self.mono_ms.load(Ordering::SeqCst)
    }

    pub fn advance(&self, ms: u64) {
        self.mono_ms.fetch_add(ms, Ordering::SeqCst);
    }
}

pub fn with_workspace<T>(f: impl FnOnce(&TestWorkspace) -> T) -> io::Result<T> {
    let workspace = TestWorkspace::new()?;
    Ok(f(&workspace))
}

fn json_path(path: &Path) -> String {
    path.to_string_lossy()
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::{with_workspace, TestWorkspace};
    use crate::UnwrapOrAbort;
    use std::sync::{Arc, Barrier};
    use std::thread;

    #[test]
    fn workspace_creates_standard_isolated_paths_and_config() {
        // arrange
        // act
        // assert
        let workspace = TestWorkspace::with_seed(7).unwrap_or_abort();

        assert!(workspace.root().exists());
        assert!(workspace.sessions_dir().is_dir());
        assert!(workspace.artifacts_dir().is_dir());
        assert!(workspace.fixtures_dir().is_dir());
        assert_eq!(workspace.seed(), 7);
        assert_eq!(workspace.ids().seed(), 7);
        assert_eq!(
            workspace.ids().next_prefixed("run"),
            "run_0000000000000007_000001"
        );

        let config = std::fs::read_to_string(workspace.config_path()).unwrap_or_abort();
        assert!(config.contains("\"enabled\": true"));
        assert!(config.contains("\"seed\": 7"));
        assert!(config.contains(workspace.sessions_dir().to_string_lossy().as_ref()));
    }

    #[test]
    fn with_workspace_cleans_up_after_scope() {
        // arrange
        // act
        // assert
        let root = with_workspace(|workspace| workspace.root().to_path_buf()).unwrap_or_abort();
        assert!(!root.exists(), "temp workspace should be removed on drop");
    }

    #[test]
    fn fake_clock_is_manual_and_deterministic() {
        // arrange
        // act
        // assert
        let workspace = TestWorkspace::new().unwrap_or_abort();
        assert_eq!(workspace.clock().mono_ms(), 0);
        workspace.clock().advance(25);
        workspace.clock().advance(17);
        assert_eq!(workspace.clock().mono_ms(), 42);
    }

    #[test]
    fn workspaces_are_safe_to_construct_concurrently() {
        // arrange
        // act
        // assert
        let workers = 4;
        let barrier = Arc::new(Barrier::new(workers));
        let handles: Vec<_> = (0..workers)
            .map(|idx| {
                let barrier = Arc::clone(&barrier);
                thread::spawn(move || {
                    barrier.wait();
                    let workspace = TestWorkspace::with_seed(idx as u64).unwrap_or_abort();
                    assert_eq!(workspace.seed(), idx as u64);
                    workspace.root().to_path_buf()
                })
            })
            .collect();

        let mut roots = handles
            .into_iter()
            .map(|handle| handle.join().unwrap_or_abort())
            .collect::<Vec<_>>();
        roots.sort();
        roots.dedup();
        assert_eq!(roots.len(), workers);
    }
}
