use harness_core::UnwrapOrAbort;
#[tokio::test]
async fn compaction_trigger_pre_prompt_runtime_uses_checkpointed_prior_context() {
    let temp_dir = tempfile::tempdir().unwrap_or_abort();
    let current_prompt = "C".repeat(12_000);
    let provider = SequentialScriptedProvider::new(vec![
        provider_text_events(&"A".repeat(12_000)),
        provider_text_events(&"B".repeat(12_000)),
        provider_text_events("third answer"),
    ]);
    let coordinator = test_agent_coordinator_with_provider_and_compaction(
        temp_dir.path(),
        Arc::new(provider.clone()),
        1,
        CompactionRuntimeConfig {
            fallback_input_tokens: 10_000,
            ..CompactionRuntimeConfig::default()
        },
    );

    let run = coordinator
        .start_run(
            "coord_pre_prompt_compaction_prior_context",
            PathBuf::from("/workspace/project"),
        )
        .await
        .unwrap_or_abort();
    let agent_id = coordinator
        .spawn_agent_idle(supervisor_actor(), "alpha", None)
        .await
        .unwrap_or_abort();
    for question in ["first question", "second question"] {
        coordinator
            .request_agent_turn(supervisor_actor(), agent_id.clone(), question)
            .await
            .unwrap_or_abort();
        tokio::task::yield_now().await;
    }
    coordinator
        .request_agent_turn(supervisor_actor(), agent_id, &current_prompt)
        .await
        .unwrap_or_abort();
    tokio::task::yield_now().await;
    coordinator.stop_run().await.unwrap_or_abort();

    let requests = provider.requests();
    assert_eq!(
        requests.len(),
        3,
        "third turn should not need an overflow retry"
    );
    let third_messages = requests
        .last()
        .unwrap_or_abort()
        .messages
        .iter()
        .map(|message| (message.role.clone(), message.content.clone()))
        .collect::<Vec<_>>();
    assert!(third_messages.iter().any(|(role, content)| {
        *role == MessageRole::Assistant
            && content.contains("Checkpoint recap generated by the harness for older turns")
    }));
    assert!(third_messages
        .iter()
        .any(|(role, content)| { *role == MessageRole::User && content == &current_prompt }));
    assert!(!third_messages
        .iter()
        .any(|(role, content)| *role == MessageRole::User && content == "first question"));

    let events = load_events(&run.events_path);
    let written = events
        .iter()
        .find_map(|event| match &event.payload {
            EventV1::CompactionWritten(payload) if payload.trigger_reason == "pre_prompt" => {
                Some(payload.clone())
            }
            _ => None,
        })
        .unwrap_or_abort();
    assert_eq!(written.tokens_before, None);
    let checkpoint_path = run.run_dir.join(&written.artifact_path);
    let checkpoint_body = fs::read_to_string(&checkpoint_path).unwrap_or_abort();
    let checkpoint_json: serde_json::Value =
        serde_json::from_str(&checkpoint_body).unwrap_or_abort();
    let recent_turns = checkpoint_json
        .get("recent_turns")
        .and_then(serde_json::Value::as_array)
        .unwrap_or_abort();
    assert!(recent_turns.iter().all(|turn| {
        turn.get("user_prompt").and_then(serde_json::Value::as_str) != Some(current_prompt.as_str())
    }));
}
#[tokio::test]
async fn compaction_no_loop_guards_cover_pre_prompt_overflow_and_failed_response() {
    let pre_prompt_dir = tempfile::tempdir().unwrap_or_abort();
    let pre_prompt_current_prompt = "C".repeat(12_000);
    let pre_prompt_provider = SequentialScriptedProvider::new(vec![
        provider_text_events(&"A".repeat(12_000)),
        provider_text_events(&"B".repeat(12_000)),
        provider_text_events("third answer after pre-prompt no-shrink"),
    ]);
    let pre_prompt = test_agent_coordinator_with_provider_and_compaction(
        pre_prompt_dir.path(),
        Arc::new(pre_prompt_provider.clone()),
        1,
        CompactionRuntimeConfig {
            fallback_input_tokens: 10_000,
            ..CompactionRuntimeConfig::default()
        },
    );
    let pre_prompt_run = pre_prompt
        .start_run(
            "coord_no_loop_pre_prompt",
            PathBuf::from("/workspace/project"),
        )
        .await
        .unwrap_or_abort();
    let pre_prompt_agent = pre_prompt
        .spawn_agent_idle(supervisor_actor(), "alpha", None)
        .await
        .unwrap_or_abort();
    for question in ["first question", "second question"] {
        pre_prompt
            .request_agent_turn(supervisor_actor(), pre_prompt_agent.clone(), question)
            .await
            .unwrap_or_abort();
        tokio::task::yield_now().await;
    }
    let pre_prompt_request_id = pre_prompt
        .request_agent_turn(
            supervisor_actor(),
            pre_prompt_agent,
            &pre_prompt_current_prompt,
        )
        .await
        .unwrap_or_abort();
    let pre_prompt_events = wait_for_events(
        &pre_prompt_run.events_path,
        Duration::from_millis(900),
        |events| {
            events.iter().any(|event| {
                matches!(
                    &event.payload,
                    EventV1::TaskCompleted(payload)
                        if event.correlation_id.as_deref() == Some(pre_prompt_request_id.as_str())
                            && payload.result_summary == "third answer after pre-prompt no-shrink"
                )
            })
        },
    )
    .await;
    pre_prompt.stop_run().await.unwrap_or_abort();
    let pre_prompt_attempt_count = pre_prompt_events
        .iter()
        .filter(|event| {
            matches!(
                &event.payload,
                EventV1::CompactionWritten(payload) if payload.trigger_reason == "pre_prompt"
            ) || matches!(
                &event.payload,
                EventV1::CompactionFailed(payload) if payload.trigger_reason == "pre_prompt"
            )
        })
        .count();
    assert_eq!(
        pre_prompt_attempt_count,
        1,
        "pre-prompt compaction should attempt at most once before provider execution; requested={}, written={}",
        pre_prompt_events
            .iter()
            .filter(|event| matches!(
                &event.payload,
                EventV1::CompactionRequested(payload) if payload.trigger_reason == "pre_prompt"
            ))
            .count(),
        pre_prompt_events
            .iter()
            .filter(|event| matches!(
                &event.payload,
                EventV1::CompactionWritten(payload) if payload.trigger_reason == "pre_prompt"
            ))
            .count()
    );
    assert_eq!(
        pre_prompt_provider.requests().len(),
        3,
        "pre-prompt no-shrink must not loop provider execution"
    );

    let overflow_dir = tempfile::tempdir().unwrap_or_abort();
    let overflow_provider = SequentialScriptedProvider::new(vec![
        provider_text_events("first answer"),
        vec![
            ProviderStreamEvent::Start,
            ProviderStreamEvent::error("prompt token count of 128713 exceeds the limit of 128000"),
        ],
    ]);
    let overflow = test_agent_coordinator_with_provider(
        overflow_dir.path(),
        Arc::new(overflow_provider.clone()),
        1,
    );
    let overflow_run = overflow
        .start_run(
            "coord_no_loop_overflow",
            PathBuf::from("/workspace/project"),
        )
        .await
        .unwrap_or_abort();
    let overflow_agent = overflow
        .spawn_agent_idle(supervisor_actor(), "alpha", None)
        .await
        .unwrap_or_abort();
    overflow
        .request_agent_turn(supervisor_actor(), overflow_agent.clone(), "first question")
        .await
        .unwrap_or_abort();
    tokio::task::yield_now().await;
    let overflow_request_id = overflow
        .request_agent_turn(supervisor_actor(), overflow_agent, "second question")
        .await
        .unwrap_or_abort();
    let overflow_events = wait_for_events(&overflow_run.events_path, Duration::from_millis(700), |events| {
        events.iter().any(|event| {
            matches!(
                &event.payload,
                EventV1::TaskCancelled(payload)
                    if event.correlation_id.as_deref() == Some(overflow_request_id.as_str())
                        && payload.reason.contains("no checkpoint reduced the active provider context")
            )
        })
    })
    .await;
    overflow.stop_run().await.unwrap_or_abort();
    assert_eq!(
        overflow_events
            .iter()
            .filter(|event| matches!(
                &event.payload,
                EventV1::CompactionFailed(payload) if payload.trigger_reason == "overflow_retry"
            ))
            .count(),
        1,
        "overflow retry no-shrink should record exactly one failed compaction attempt"
    );
    assert_eq!(
        overflow_provider.requests().len(),
        2,
        "overflow no-shrink must not resend the same context"
    );
    assert!(overflow_events.iter().any(|event| {
        matches!(
            &event.payload,
            EventV1::TaskCancelled(payload)
                if event.correlation_id.as_deref() == Some(overflow_request_id.as_str())
                    && payload.reason.contains("prompt token count")
        )
    }));

    let failed_dir = tempfile::tempdir().unwrap_or_abort();
    let failed_provider = SequentialScriptedProvider::new(vec![
        provider_text_events("first answer"),
        vec![
            ProviderStreamEvent::Start,
            ProviderStreamEvent::TextDelta(format!(
                "partial provider output {}",
                "B".repeat(35_100)
            )),
            ProviderStreamEvent::error("provider exploded"),
        ],
    ]);
    let failed = test_agent_coordinator_with_provider_and_compaction(
        failed_dir.path(),
        Arc::new(failed_provider.clone()),
        1,
        CompactionRuntimeConfig {
            fallback_input_tokens: 10_000,
            ..CompactionRuntimeConfig::default()
        },
    );
    let failed_run = failed
        .start_run(
            "coord_no_loop_failed_response",
            PathBuf::from("/workspace/project"),
        )
        .await
        .unwrap_or_abort();
    let failed_agent = failed
        .spawn_agent_idle(supervisor_actor(), "alpha", None)
        .await
        .unwrap_or_abort();
    failed
        .request_agent_turn(supervisor_actor(), failed_agent.clone(), "first question")
        .await
        .unwrap_or_abort();
    wait_for_events(
        &failed_run.events_path,
        Duration::from_millis(700),
        |events| {
            events.iter().any(|event| {
                matches!(
                    &event.payload,
                    EventV1::TaskCompleted(payload) if payload.result_summary == "first answer"
                )
            })
        },
    )
    .await;
    let failed_request_id = failed
        .request_agent_turn(supervisor_actor(), failed_agent, "partial then error")
        .await
        .unwrap_or_abort();
    let failed_events = wait_for_events(
        &failed_run.events_path,
        Duration::from_millis(900),
        |events| {
            events.iter().any(|event| {
            matches!(
                &event.payload,
                EventV1::TaskCancelled(payload)
                    if event.correlation_id.as_deref() == Some(failed_request_id.as_str())
                        && payload.reason == "provider exploded"
            )
        }) && events.iter().any(|event| {
            matches!(
                &event.payload,
                EventV1::CompactionFailed(payload)
                    if payload.trigger_reason == "failed_response"
                        && payload.through_request_id.as_deref() == Some(failed_request_id.as_str())
            )
        })
        },
    )
    .await;
    failed.stop_run().await.unwrap_or_abort();
    assert_eq!(
        failed_events
            .iter()
            .filter(|event| matches!(
                &event.payload,
                EventV1::CompactionFailed(payload)
                    if payload.trigger_reason == "failed_response"
                        && payload.through_request_id.as_deref() == Some(failed_request_id.as_str())
            ))
            .count(),
        1,
        "failed-response no-shrink should record exactly one failed compaction attempt"
    );
    assert_eq!(
        failed_provider.requests().len(),
        2,
        "failed-response no-shrink must not retry the provider turn"
    );
    assert!(failed_events.iter().any(|event| {
        matches!(
            &event.payload,
            EventV1::TaskCancelled(payload)
                if event.correlation_id.as_deref() == Some(failed_request_id.as_str())
                    && payload.reason == "provider exploded"
        )
    }));
}
#[tokio::test]
async fn manual_compaction_writes_checkpoint_and_manual_events() {
    let temp_dir = tempfile::tempdir().unwrap_or_abort();
    let provider = SequentialScriptedProvider::new(vec![
        vec![
            ProviderStreamEvent::Start,
            ProviderStreamEvent::TextDelta("A".repeat(12_000)),
            ProviderStreamEvent::Done {
                usage: CompletionUsage {
                    prompt_tokens: 100,
                    completion_tokens: 100,
                    total_tokens: 200,
                },
            },
        ],
        vec![
            ProviderStreamEvent::Start,
            ProviderStreamEvent::TextDelta("B".repeat(12_000)),
            ProviderStreamEvent::Done {
                usage: CompletionUsage {
                    prompt_tokens: 100,
                    completion_tokens: 100,
                    total_tokens: 200,
                },
            },
        ],
    ]);
    let coordinator =
        test_agent_coordinator_with_provider(temp_dir.path(), Arc::new(provider.clone()), 1);

    let run = coordinator
        .start_run(
            "coord_manual_compaction",
            PathBuf::from("/workspace/project"),
        )
        .await
        .unwrap_or_abort();

    let agent_id = coordinator
        .spawn_agent_idle(supervisor_actor(), "alpha", None)
        .await
        .unwrap_or_abort();
    coordinator
        .request_agent_turn(supervisor_actor(), agent_id.clone(), "first question")
        .await
        .unwrap_or_abort();
    tokio::task::yield_now().await;
    let second_request_id = coordinator
        .request_agent_turn(supervisor_actor(), agent_id.clone(), "second question")
        .await
        .unwrap_or_abort();
    tokio::task::yield_now().await;

    let outcome = coordinator
        .compact_agent_context(agent_id, Some(second_request_id.clone()), "manual")
        .await
        .unwrap_or_abort();
    let ManualCompactionOutcome::CheckpointWritten {
        checkpoint_id,
        tokens_before_estimate,
        tokens_after_estimate,
    } = outcome
    else {
        panic!("expected checkpoint to be written");
    };
    assert!(tokens_before_estimate.is_some());
    assert!(tokens_after_estimate.is_some());
    assert!(tokens_after_estimate < tokens_before_estimate);

    coordinator.stop_run().await.unwrap_or_abort();

    let events = load_events(&run.events_path);
    assert!(events.iter().any(|event| {
        matches!(
            &event.payload,
            EventV1::CompactionRequested(payload)
                if payload.agent_id == "agent_000001"
                    && payload.trigger_reason == "manual"
                    && payload.through_request_id.as_deref() == Some(second_request_id.as_str())
                    && payload.checkpoint_id == checkpoint_id
        )
    }));
    let written = events
        .iter()
        .find_map(|event| match &event.payload {
            EventV1::CompactionWritten(payload) if payload.trigger_reason == "manual" => {
                Some(payload.clone())
            }
            _ => None,
        })
        .unwrap_or_abort();
    assert_eq!(written.checkpoint_id, checkpoint_id);
    assert_eq!(written.tokens_before_estimate, tokens_before_estimate);
    assert_eq!(written.tokens_after_estimate, tokens_after_estimate);
    assert_eq!(written.compacted_turns, Some(1));
    assert_eq!(
        written.through_request_id.as_deref(),
        Some(second_request_id.as_str())
    );
    assert!(events.iter().any(|event| {
        matches!(
            &event.payload,
            EventV1::CompactionApplied(payload)
                if payload.checkpoint_id == checkpoint_id
                    && payload.through_request_id.as_deref() == Some(second_request_id.as_str())
                    && payload.tokens_before_estimate == tokens_before_estimate
                    && payload.tokens_after_estimate == tokens_after_estimate
        )
    }));
    let checkpoint_path = run.run_dir.join(&written.artifact_path);
    assert!(
        checkpoint_path.exists(),
        "checkpoint artifact should be written"
    );
}
