pub const ENDPOINT: &str = "HARNESS_REMOTE_SEARCH_ENDPOINT";
pub const AUTH_TOKEN: &str = "HARNESS_REMOTE_SEARCH_AUTH_TOKEN";
pub const REQUIRE_AUTH: &str = "HARNESS_REMOTE_SEARCH_REQUIRE_AUTH";
pub const TIMEOUT_SECS: &str = "HARNESS_REMOTE_SEARCH_TIMEOUT_SECS";
pub const MAX_RETRIES: &str = "HARNESS_REMOTE_SEARCH_MAX_RETRIES";
pub const RETRY_BACKOFF_MS: &str = "HARNESS_REMOTE_SEARCH_RETRY_BACKOFF_MS";
