[package]
name = "harness-tui"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0"
ratatui.workspace = true
crossterm = { workspace = true, features = ["event-stream"] }
harness-core = { path = "../harness-core" }
futures = "0.3.32"
futures-util = "0.3.32"
imara-diff = "0.2"
serde_json.workspace = true
syntect = { version = "5.3", default-features = false, features = ["default-fancy"] }

[dev-dependencies]
insta = { version = "1.39", features = ["json"] }
tempfile.workspace = true
portable-pty = "0.8"
vt100 = "0.15"
