[package]
name = "harness-tui"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0"
ratatui.workspace = true
crossterm = { workspace = true, features = ["event-stream"] }
crossbeam-channel = "0.5"
harness-core = { path = "../harness-core" }
futures = "0.3.32"
futures-util = "0.3.32"
serde_json.workspace = true

[dev-dependencies]
insta = { version = "1.39", features = ["json"] }
tempfile.workspace = true
