[package]
name = "harness-core"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
humantime = "2.1"
serde.workspace = true
serde_json.workspace = true
json5.workspace = true
schemars.workspace = true
thiserror.workspace = true
async-trait = "0.1"
regex = "1"
blake3 = "1"
getrandom = "0.3"
sha2 = "0.10"
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tracing = "0.1"
which = "7"
similar = "2.7.0"
harness-providers = { path = "../harness-providers" }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "blocking"] }

[dev-dependencies]
tempfile.workspace = true
insta = { version = "1.42", features = ["json"] }
proptest = "1"

[lints]
workspace = true
