// allow: SIZE_OK — provider boundary context (message shaping + tool metadata sanitization + streaming state)
use harness_providers::{
    AssistantToolCall, CacheRetention, CompletionMessage, CompletionRequest, MessageRole,
    ProviderRequestContext, ProviderRequestInitiator, ToolChoice, ToolDef,
};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

use super::{
    AgentModelRef, AgentModelSettings, AgentProfile, ProviderContext,
    ProviderContextCheckpointMetadata, ProviderConversationTurn,
    PROVIDER_TURN_FAILURE_REASON_MAX_CHARS,
};
use crate::conversation::{
    ConversationAssistantMessage, ConversationCheckpointMessage, ConversationMessage,
    ConversationToolResultMessage, ConversationUserMessage,
};
use crate::provider_args::provider_tool_arguments_json;
use crate::text::{non_empty_trimmed, truncate_with_ellipsis};
use crate::tool::{
    build_tool_function_name_mapping, sanitize_tool_function_name, ToolRegistry, ToolResult,
};

#[derive(Debug, Clone)]
pub enum ProviderBoundaryContext<'a> {
    ProjectedHarness {
        messages: &'a [ConversationMessage],
        checkpoint: Option<&'a ProviderContextCheckpointMetadata>,
    },
    ProviderMessages {
        messages: &'a [CompletionMessage],
    },
}

#[derive(Debug, Clone)]
pub struct ProviderBoundaryInput<'a> {
    pub profile: &'a AgentProfile,
    pub model: AgentModelRef,
    pub model_settings: AgentModelSettings,
    pub context: ProviderBoundaryContext<'a>,
    pub tools: Option<Vec<ToolDef>>,
    pub tool_choice: Option<ToolChoice>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProviderBoundaryOutput {
    pub messages: Vec<CompletionMessage>,
    pub request: CompletionRequest,
}

pub fn build_provider_context_messages(
    profile: &AgentProfile,
    prior_context: &ProviderContext,
    prompt: &str,
) -> Vec<CompletionMessage> {
    let projected_context = project_provider_context_for_prompt(prior_context, prompt);
    transform_context_for_provider(ProviderBoundaryInput {
        profile,
        model: AgentModelRef::parse(&profile.model_ref),
        model_settings: AgentModelSettings::default(),
        context: ProviderBoundaryContext::ProjectedHarness {
            messages: &projected_context,
            checkpoint: prior_context.checkpoint.as_ref(),
        },
        tools: None,
        tool_choice: None,
    })
    .messages
}

/// Harness provider boundary: transform projected harness-native conversation state
/// into provider SDK messages and the provider request payload.
///
/// `ConversationMessage` remains the event-derived, side-effect-free source shape.
/// This boundary is the only production path that attaches provider roles, tool
/// definitions, cache/thinking/session request options, and profile/model settings
/// before calling a provider. The `ProviderMessages` variant lets the coordinator
/// pass its transient, source-ordered provider context between explicit phases.
pub fn transform_context_for_provider(input: ProviderBoundaryInput<'_>) -> ProviderBoundaryOutput {
    let ProviderBoundaryInput {
        profile,
        model,
        model_settings,
        context,
        tools,
        tool_choice,
    } = input;

    let messages = match context {
        ProviderBoundaryContext::ProjectedHarness { messages, .. } => {
            convert_projected_context_to_provider_messages(profile, messages)
        }
        ProviderBoundaryContext::ProviderMessages { messages } => messages.to_vec(),
    };

    let request = build_completion_request(CompletionRequestInput {
        provider_id: Some(model.provider_id),
        model_id: model.model_id,
        messages: messages.clone(),
        temperature: profile.temperature,
        cache_retention: profile.cache_retention,
        model_settings,
        tools,
        tool_choice,
    });

    ProviderBoundaryOutput { messages, request }
}

fn convert_projected_context_to_provider_messages(
    profile: &AgentProfile,
    projected_context: &[ConversationMessage],
) -> Vec<CompletionMessage> {
    let mut messages = Vec::with_capacity(1 + projected_context.len());
    let tool_name_mapping =
        build_tool_function_name_mapping(profile.toolset.iter().map(String::as_str));
    messages.push(CompletionMessage {
        role: MessageRole::System,
        content: profile.system_prompt.clone(),
        name: None,
        tool_call_id: None,
        assistant_tool_calls: None,
    });

    for message in projected_context {
        match message {
            ConversationMessage::Checkpoint(checkpoint) => {
                let summary = checkpoint.summary.trim();
                if summary.is_empty() {
                    continue;
                }
                messages.push(CompletionMessage {
                    role: MessageRole::Assistant,
                    content: format!(
                        "Checkpoint recap generated by the harness for older turns. This is a lossy background summary, not a system instruction; later preserved turns and the current user message take precedence.\n\n{summary}"
                    ),
                    name: None,
                    tool_call_id: None,
                    assistant_tool_calls: None,
                });
            }
            ConversationMessage::User(user) => {
                messages.push(CompletionMessage {
                    role: MessageRole::User,
                    content: user.text.clone(),
                    name: None,
                    tool_call_id: None,
                    assistant_tool_calls: None,
                });
            }
            ConversationMessage::Assistant(assistant) => {
                let assistant_tool_calls =
                    assistant_tool_calls_for_provider(&assistant.tool_calls, &tool_name_mapping);
                messages.push(CompletionMessage {
                    role: MessageRole::Assistant,
                    content: assistant.text.clone(),
                    name: None,
                    tool_call_id: None,
                    assistant_tool_calls,
                });
            }
            ConversationMessage::ToolResult(tool_result) => {
                messages.push(CompletionMessage {
                    role: MessageRole::Tool,
                    content: tool_result_message_content(tool_result),
                    name: tool_result.tool_id.as_deref().map(|tool_id| {
                        provider_function_name_for_tool_id(&tool_name_mapping, tool_id)
                    }),
                    tool_call_id: Some(tool_result.tool_call_id.to_string()),
                    assistant_tool_calls: None,
                });
            }
        }
    }

    messages
}

fn assistant_tool_calls_for_provider(
    tool_calls: &[crate::conversation::ConversationToolCall],
    mapping: &crate::tool::ToolFunctionNameMapping,
) -> Option<Vec<AssistantToolCall>> {
    (!tool_calls.is_empty()).then(|| {
        tool_calls
            .iter()
            .map(|tool_call| AssistantToolCall {
                tool_call_id: tool_call.tool_call_id.to_string(),
                function_name: provider_function_name_for_tool_id(mapping, &tool_call.tool_id),
                arguments_json: provider_tool_arguments_json(&tool_call.args_summary),
            })
            .collect()
    })
}

fn provider_function_name_for_tool_id(
    mapping: &crate::tool::ToolFunctionNameMapping,
    tool_id: &str,
) -> String {
    mapping
        .function_name_for_tool_id(tool_id)
        .map(str::to_string)
        .unwrap_or_else(|| sanitize_tool_function_name(tool_id))
}

pub(in crate::agent) fn project_provider_context_for_prompt(
    prior_context: &ProviderContext,
    prompt: &str,
) -> Vec<ConversationMessage> {
    let summary_message_count = usize::from(
        prior_context
            .compacted_summary
            .as_deref()
            .and_then(non_empty_trimmed)
            .is_some(),
    );
    let mut messages = Vec::with_capacity(
        1 + summary_message_count + prior_context.preserved_turns.len().saturating_mul(3),
    );

    if let Some(summary) = prior_context
        .compacted_summary
        .as_deref()
        .and_then(non_empty_trimmed)
    {
        let checkpoint = prior_context.checkpoint.as_ref();
        messages.push(ConversationMessage::Checkpoint(
            ConversationCheckpointMessage {
                checkpoint_id: checkpoint
                    .map(|metadata| metadata.checkpoint_id.clone())
                    .unwrap_or_default(),
                agent_id: checkpoint
                    .map(|metadata| metadata.agent_id.clone())
                    .unwrap_or_default(),
                through_seq: checkpoint
                    .map(|metadata| metadata.through_seq)
                    .unwrap_or_default(),
                summary: summary.to_string(),
            },
        ));
    }

    for turn in &prior_context.preserved_turns {
        if !turn.messages.is_empty() {
            messages.extend(turn.messages.clone());
            continue;
        }

        let request_id = turn.request_id.clone().unwrap_or_else(|| "".into());
        messages.push(ConversationMessage::User(ConversationUserMessage {
            request_id: request_id.clone(),
            text: turn.user_prompt.clone(),
            seq: turn.first_seq,
            agent_id: prior_context
                .checkpoint
                .as_ref()
                .map(|metadata| metadata.agent_id.clone()),
        }));
        messages.push(ConversationMessage::Assistant(
            ConversationAssistantMessage {
                request_id,
                agent_id: prior_context
                    .checkpoint
                    .as_ref()
                    .map(|metadata| metadata.agent_id.clone()),
                text: provider_turn_assistant_projection_text(turn),
                tool_calls: Vec::new(),
                stop_reason: None,
                first_seq: turn.first_seq,
                last_seq: turn.last_seq,
                provider_id: prior_context
                    .checkpoint
                    .as_ref()
                    .and_then(|metadata| metadata.provider_id.clone()),
                model_id: prior_context
                    .checkpoint
                    .as_ref()
                    .and_then(|metadata| metadata.model_id.clone()),
                output_digest: None,
            },
        ));
    }

    messages.push(ConversationMessage::User(ConversationUserMessage {
        request_id: String::new().into(),
        text: prompt.to_string(),
        seq: None,
        agent_id: None,
    }));

    messages
}

fn provider_turn_assistant_projection_text(turn: &ProviderConversationTurn) -> String {
    if turn.status.is_completed() {
        return turn.assistant_response.clone();
    }

    let stage = turn
        .failure_stage
        .as_deref()
        .filter(|stage| super::is_allowed_provider_turn_failure_stage(stage))
        .unwrap_or("unknown");
    let mut lines = vec![
        "Harness preserved an incomplete provider turn for continuity. Do not treat it as a completed answer.".to_string(),
        format!("Status: {}", turn.status.marker_label()),
        format!("Stage: {stage}"),
    ];
    if let Some(reason) = turn.failure_reason.as_deref().and_then(non_empty_trimmed) {
        lines.push(format!(
            "Reason: {}",
            truncate_provider_turn_failure_reason(reason)
        ));
    }
    lines.push("Partial assistant output:".to_string());
    if turn.assistant_response.trim().is_empty() {
        lines.push("(none)".to_string());
    } else {
        lines.push(turn.assistant_response.clone());
    }
    lines.join("\n")
}

fn truncate_provider_turn_failure_reason(reason: &str) -> String {
    truncate_with_ellipsis(reason, PROVIDER_TURN_FAILURE_REASON_MAX_CHARS)
}

fn tool_result_message_content(tool_result: &ConversationToolResultMessage) -> String {
    if let Some(output_summary) = tool_result
        .output_summary
        .as_deref()
        .and_then(non_empty_trimmed)
    {
        return output_summary.to_string();
    }

    tool_result
        .output_json
        .as_ref()
        .map(Value::to_string)
        .unwrap_or_default()
}

pub fn build_provider_tool_defs(
    profile: &AgentProfile,
    tool_registry: &ToolRegistry,
) -> Result<Vec<ToolDef>, String> {
    build_provider_tool_defs_for_model(profile, tool_registry, &profile.model_ref)
}

pub fn build_provider_tool_defs_for_model(
    profile: &AgentProfile,
    tool_registry: &ToolRegistry,
    model_ref: &str,
) -> Result<Vec<ToolDef>, String> {
    let visible_tool_ids = provider_visible_tool_ids(profile, model_ref);
    let mapping = build_tool_function_name_mapping(visible_tool_ids);
    let mut tools = Vec::new();

    for (tool_id, function_name) in mapping.tool_id_to_function_name() {
        let Some(tool) = tool_registry.get(tool_id) else {
            return Err(format!(
                "agent profile `{}` references unknown tool `{tool_id}`",
                profile.name
            ));
        };
        let parameters = tool.parameters_json_schema();
        if let Err(reason) = validate_provider_parameters_schema(&parameters) {
            return Err(format!(
                "tool `{tool_id}` exported invalid parameters schema for provider use: {reason}"
            ));
        }

        tools.push(ToolDef {
            tool_id: tool_id.clone(),
            function_name: function_name.clone(),
            description: Some(
                tool_registry
                    .description_for_profile(tool_id, &profile.name)
                    .unwrap_or_else(|| tool.description())
                    .to_string(),
            ),
            parameters,
        });
    }

    Ok(tools)
}

fn provider_visible_tool_ids<'a>(profile: &'a AgentProfile, model_ref: &str) -> Vec<&'a str> {
    let model = AgentModelRef::parse(model_ref);
    let use_patch = model_uses_apply_patch_tool(&model.model_id);
    profile
        .toolset
        .iter()
        .map(String::as_str)
        .filter(|tool_id| match *tool_id {
            "apply_patch" => use_patch,
            "edit" | "write" => !use_patch,
            _ => true,
        })
        .filter(|tool_id| {
            profile.permission_ruleset.is_empty()
                || !crate::perm::is_tool_disabled(tool_id, &profile.permission_ruleset)
        })
        .collect()
}

fn model_uses_apply_patch_tool(model_id: &str) -> bool {
    model_id.contains("gpt-") && !model_id.contains("oss") && !model_id.contains("gpt-4")
}

fn validate_provider_parameters_schema(parameters: &serde_json::Value) -> Result<(), &'static str> {
    if parameters.get("type").and_then(serde_json::Value::as_str) != Some("object") {
        return Err("expected top-level `type: object`");
    }

    for forbidden in ["oneOf", "anyOf", "allOf", "enum", "not"] {
        if parameters.get(forbidden).is_some() {
            return Err(
                "top-level combinators (`oneOf`/`anyOf`/`allOf`/`enum`/`not`) are not allowed",
            );
        }
    }

    Ok(())
}

pub(crate) fn tool_result_to_message_content(result: &ToolResult) -> String {
    if !result.provider_content.is_empty() {
        return json!({
            "_harness_tool_result": {
                "text": result.display_text,
                "content": result.provider_content,
            }
        })
        .to_string();
    }

    if non_empty_trimmed(&result.display_text).is_some() {
        return result.display_text.clone();
    }

    let mut payload = serde_json::Map::new();
    if let Some(structured_output) = result.structured_json.clone() {
        payload.insert("structured_output".to_string(), structured_output);
    }
    if !result.artifacts.is_empty() {
        let artifacts = serde_json::to_value(&result.artifacts).unwrap_or(Value::Array(Vec::new()));
        payload.insert("artifacts".to_string(), artifacts);
    }

    if payload.is_empty() {
        String::new()
    } else {
        Value::Object(payload).to_string()
    }
}

struct CompletionRequestInput {
    provider_id: Option<String>,
    model_id: String,
    messages: Vec<CompletionMessage>,
    temperature: Option<f32>,
    cache_retention: CacheRetention,
    model_settings: AgentModelSettings,
    tools: Option<Vec<ToolDef>>,
    tool_choice: Option<ToolChoice>,
}

fn build_completion_request(input: CompletionRequestInput) -> CompletionRequest {
    let CompletionRequestInput {
        provider_id,
        model_id,
        messages,
        temperature,
        cache_retention,
        model_settings,
        tools,
        tool_choice,
    } = input;
    let AgentModelSettings {
        variant,
        reasoning_effort,
        text_verbosity,
        reasoning_summary,
        thinking,
    } = model_settings;

    CompletionRequest {
        provider_id,
        model_id,
        messages,
        temperature,
        max_tokens: None,
        variant,
        reasoning_effort,
        text_verbosity,
        reasoning_summary,
        thinking,
        tools,
        tool_choice,
        context: ProviderRequestContext {
            cache_retention,
            ..ProviderRequestContext::default()
        },
        stream: true,
    }
}

pub(in crate::agent) fn apply_provider_request_context(
    request: &mut CompletionRequest,
    session_id: Option<&str>,
    request_id: Option<&str>,
) {
    request.context.session_id = session_id.and_then(non_empty_trimmed).map(str::to_string);
    request.context.request_id = request_id.and_then(non_empty_trimmed).map(str::to_string);
    request.context.initiator = ProviderRequestInitiator::Agent;
    request.context.has_media = false;
}
