use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};

use super::*;
use crossterm::event::KeyCode;
use harness_core::event::EventEnvelopeV1;

macro_rules! delegate_test {
    ($name:ident => $target:path) => {
        #[cfg(test)]
        #[test]
        fn $name() {
            $target();
        }
    };
}

delegate_test!(replay_mode_snapshot_renders_two_pane_layout => tests::module_replay_mode_snapshot_renders_two_pane_layout);
delegate_test!(transcript_edit_snapshot_renders_inline_diff => tests::module_transcript_edit_snapshot_renders_inline_diff);
delegate_test!(inline_diff_does_not_leave_large_gap_before_active_footer => tests::module_inline_diff_does_not_leave_large_gap_before_active_footer);
delegate_test!(transcript_edit_tool_wide_diff_uses_syntax_highlighting_and_split_palettes => tests::module_transcript_edit_tool_wide_diff_uses_syntax_highlighting_and_split_palettes);
delegate_test!(fenced_code_highlighting_uses_syntect_styles_for_known_languages => tests::module_fenced_code_highlighting_uses_syntect_styles_for_known_languages);
delegate_test!(fenced_code_highlighting_falls_back_to_plain_text_when_unknown => tests::module_fenced_code_highlighting_falls_back_to_plain_text_when_unknown);
delegate_test!(transcript_section_model_preserves_activity_order => ui::exact_test_transcript_section_model_preserves_activity_order);
delegate_test!(transcript_section_model_keeps_nested_tool_and_error_blocks => ui::exact_test_transcript_section_model_keeps_nested_tool_and_error_blocks);
delegate_test!(transcript_reasoning_precedes_answer_and_tool_rows => ui::exact_test_transcript_reasoning_precedes_answer_and_tool_rows);
delegate_test!(latest_assistant_footer_stays_after_trailing_tool_rows => ui::exact_test_latest_assistant_footer_stays_after_trailing_tool_rows);
delegate_test!(transcript_tool_rows_follow_chronological_turn_order => ui::exact_test_transcript_tool_rows_follow_chronological_turn_order);
delegate_test!(transcript_applied_edit_missing_diff_surfaces_fallback => ui::exact_test_transcript_applied_edit_missing_diff_surfaces_fallback);
delegate_test!(transcript_edit_tool_matches_inline_diff_shape => ui::exact_test_transcript_edit_tool_matches_inline_diff_shape);
delegate_test!(transcript_native_edit_renders_inline_diff_from_artifact => ui::exact_test_transcript_native_edit_renders_inline_diff_from_artifact);
delegate_test!(transcript_harness_tool_progress_indicators => ui::exact_test_transcript_harness_tool_progress_indicators);
delegate_test!(transcript_apply_patch_multifile_uses_output_edit_paths => ui::exact_test_transcript_apply_patch_multifile_uses_output_edit_paths);
delegate_test!(subagent_footer_matches_harness_layout => ui::exact_test_subagent_footer_matches_harness_layout);
delegate_test!(subagent_replay_suppresses_parent_replay_dock => ui::exact_test_subagent_replay_suppresses_parent_replay_dock);
delegate_test!(transcript_apply_patch_surfaces_rename_and_wrapped_inline_diffs => ui::exact_test_transcript_apply_patch_surfaces_rename_and_wrapped_inline_diffs);
delegate_test!(transcript_inline_diff_stays_compact_between_tool_rows => ui::exact_test_transcript_inline_diff_stays_compact_between_tool_rows);
delegate_test!(transcript_proposed_edit_renders_header => ui::exact_test_transcript_proposed_edit_renders_header);
delegate_test!(transcript_rejected_edit_surfaces_reason_inline => ui::exact_test_transcript_rejected_edit_surfaces_reason_inline);
delegate_test!(transcript_follow_mode_uses_measured_surface_heights => ui::exact_test_transcript_follow_mode_uses_measured_surface_heights);
delegate_test!(transcript_scroll_offset_preserves_large_overflow => ui::exact_test_transcript_scroll_offset_preserves_large_overflow);
delegate_test!(visible_surface_lines_support_large_offsets => ui::exact_test_visible_surface_lines_support_large_offsets);
delegate_test!(native_tool_transcript_rows_show_disclosure_timestamps_and_task_metadata => ui::exact_test_native_tool_transcript_rows_show_disclosure_timestamps_and_task_metadata);
delegate_test!(mcp_tool_transcript_rows_use_effective_identity_without_generic_fallback => ui::exact_test_mcp_tool_transcript_rows_use_effective_identity_without_generic_fallback);
delegate_test!(generic_tool_successful_output_prefers_inline_background_rows => ui::exact_test_generic_tool_successful_output_prefers_inline_background_rows);
delegate_test!(lsp_tool_successful_output_stays_hidden_until_generic_output_enabled => ui::exact_test_lsp_tool_successful_output_stays_hidden_until_generic_output_enabled);
delegate_test!(todo_write_rows_render_open_checklist => ui::exact_test_todo_write_rows_render_open_checklist);
delegate_test!(transcript_task_rows_show_child_status_duration_and_counts => ui::exact_test_transcript_task_rows_show_child_status_duration_and_counts);
delegate_test!(block_tool_cards_skip_empty_subtitle_rows => ui::exact_test_block_tool_cards_skip_empty_subtitle_rows);
delegate_test!(inline_tool_rows_wrap_long_subtitles_cleanly => ui::exact_test_inline_tool_rows_wrap_long_subtitles_cleanly);
delegate_test!(transcript_pending_permission_stays_after_last_activity => ui::exact_test_transcript_pending_permission_stays_after_last_activity);

mod transcript_turn_sections;
delegate_test!(transcript_turn_sections_render_open_rail_surfaces => transcript_turn_sections::transcript_turn_sections_render_open_rail_surfaces);
delegate_test!(transcript_turn_sections_keep_nested_tool_details => transcript_turn_sections::transcript_turn_sections_keep_nested_tool_details);

delegate_test!(operator_rail_section_model_builds_pinned_summary => ui::exact_test_operator_rail_section_model_builds_pinned_summary);
delegate_test!(compaction_applied_updates_active_context_usage_estimate => ui::exact_test_compaction_applied_updates_active_context_usage_estimate);
delegate_test!(operator_rail_sanitizes_control_chars_in_sidebar_strings => ui::exact_test_operator_rail_sanitizes_control_chars_in_sidebar_strings);
delegate_test!(operator_rail_section_model_hides_empty_sources_but_preserves_order => ui::exact_test_operator_rail_section_model_hides_empty_sources_but_preserves_order);
delegate_test!(operator_rail_section_model_counts_generic_mcp_activity => ui::exact_test_operator_rail_section_model_counts_generic_mcp_activity);
delegate_test!(operator_rail_section_model_separates_mcp_from_native_tool_activity => ui::exact_test_operator_rail_section_model_separates_mcp_from_native_tool_activity);
delegate_test!(operator_rail_section_model_uses_runtime_mcp_activity_without_config => ui::exact_test_operator_rail_section_model_uses_runtime_mcp_activity_without_config);
delegate_test!(operator_rail_section_model_keeps_native_prefix_tools_out_of_mcp => ui::exact_test_operator_rail_section_model_keeps_native_prefix_tools_out_of_mcp);
delegate_test!(operator_rail_matches_sidebar_text_styles => ui::exact_test_operator_rail_matches_sidebar_text_styles);
delegate_test!(operator_rail_uses_generated_session_title => ui::exact_test_operator_rail_uses_generated_session_title);
delegate_test!(operator_rail_renders_todo_items_from_tool_state => ui::exact_test_operator_rail_renders_todo_items_from_tool_state);
delegate_test!(operator_rail_places_todo_below_subagents => ui::exact_test_operator_rail_places_todo_below_subagents);
delegate_test!(operator_rail_renders_todo_items_from_artifact_state => ui::exact_test_operator_rail_renders_todo_items_from_artifact_state);
delegate_test!(operator_rail_renders_subagent_rows_from_orchestration_state => ui::exact_test_operator_rail_renders_subagent_rows_from_orchestration_state);
delegate_test!(operator_rail_marks_background_subagent_terminal_from_notification => ui::exact_test_operator_rail_marks_background_subagent_terminal_from_notification);
delegate_test!(operator_rail_uses_simple_subagent_task_labels => ui::exact_test_operator_rail_uses_simple_subagent_task_labels);
delegate_test!(operator_rail_shows_wakeup_report_without_task_tool_row => ui::exact_test_operator_rail_shows_wakeup_report_without_task_tool_row);
delegate_test!(operator_rail_shows_replay_wakeup_report_without_task_tool_row => ui::exact_test_operator_rail_shows_replay_wakeup_report_without_task_tool_row);
delegate_test!(operator_rail_keeps_subagents_visible_in_replay => ui::exact_test_operator_rail_keeps_subagents_visible_in_replay);
delegate_test!(operator_rail_hides_completed_todo_state => ui::exact_test_operator_rail_hides_completed_todo_state);
delegate_test!(operator_rail_collapses_todo_section_body => ui::exact_test_operator_rail_collapses_todo_section_body);
delegate_test!(operator_rail_collapses_modified_files_section_body => ui::exact_test_operator_rail_collapses_modified_files_section_body);
delegate_test!(operator_sidebar_hit_target_maps_section_headers => ui::exact_test_operator_sidebar_hit_target_maps_section_headers);

mod operator_sidebar;
delegate_test!(operator_sidebar_pins_summary_and_hides_empty_sections => operator_sidebar::operator_sidebar_pins_summary_and_hides_empty_sections);
delegate_test!(operator_sidebar_compact_empty_mode_preserves_anchor_copy_with_fixed_width => operator_sidebar::operator_sidebar_compact_empty_mode_preserves_anchor_copy_with_fixed_width);
delegate_test!(operator_sidebar_width_stays_fixed_when_todo_or_modified_files_exist => operator_sidebar::operator_sidebar_width_stays_fixed_when_todo_or_modified_files_exist);

delegate_test!(persistent_operator_sidebar_uses_panel_gutter_instead_of_border_line => ui::exact_test_persistent_operator_sidebar_uses_panel_gutter);
delegate_test!(control_dock_view_model_handles_live_runtime_variants => view_model::exact_test_control_dock_view_model_handles_live_runtime_variants);
delegate_test!(control_dock_view_model_preserves_replay_read_only_variant => view_model::exact_test_control_dock_view_model_preserves_replay_read_only_variant);
delegate_test!(tool_runtime_state_uses_effective_tool_identity => view_model::exact_test_tool_runtime_state_uses_effective_tool_identity);
delegate_test!(startup_shell_keeps_no_default_tab_chrome_after_runtime_context_addition => ui::exact_test_startup_shell_keeps_no_default_tab_chrome_after_runtime_context_addition);
delegate_test!(replay_prompt_pane_is_visibly_read_only => ui::exact_test_replay_prompt_pane_is_visibly_read_only);
delegate_test!(live_control_dock_renders_shared_surface => ui::exact_test_live_control_dock_renders_shared_surface);
delegate_test!(live_control_dock_collapses_disclosure_before_status => ui::exact_test_live_control_dock_collapses_disclosure_before_status);
delegate_test!(live_composer_metadata_omits_success_without_variant => ui::exact_test_live_composer_metadata_omits_success_without_variant);
delegate_test!(live_composer_reserves_right_gap => ui::exact_test_live_composer_reserves_right_gap);
delegate_test!(live_composer_disclosure_summarizes_compaction_metrics => ui::exact_test_live_composer_disclosure_summarizes_compaction_metrics);
delegate_test!(startup_disclosure_matches_harness_hint_row => ui::exact_test_startup_disclosure_matches_harness_hint_row);
delegate_test!(composer_viewport_wraps_by_display_width => ui::exact_test_composer_viewport_wraps_by_display_width);
delegate_test!(composer_viewport_wraps_at_word_boundaries => ui::exact_test_composer_viewport_wraps_at_word_boundaries);
delegate_test!(tool_status_summary_uses_effective_tool_identity => ui::exact_test_tool_status_summary_uses_effective_tool_identity);
delegate_test!(footer_status_cluster_shows_pending_permission_count => ui::exact_test_footer_status_cluster_shows_pending_permission_count);
delegate_test!(footer_status_cluster_empty_when_no_activity => ui::exact_test_footer_status_cluster_empty_when_no_activity);
delegate_test!(retry_summary_segment_prioritizes_retry_indicator => ui::exact_test_retry_summary_segment_prioritizes_retry_indicator);
delegate_test!(wheel_target_hits_transcript_when_hovered => ui::exact_test_wheel_target_hits_transcript_when_hovered);
delegate_test!(wheel_target_hits_inspector_inside_live_overlay => ui::exact_test_wheel_target_hits_inspector_inside_live_overlay);
delegate_test!(wheel_target_excludes_activity_portion_of_live_overlay => ui::exact_test_wheel_target_excludes_activity_portion_of_live_overlay);
delegate_test!(compact_operator_rail_does_not_capture_wheel => ui::exact_test_compact_operator_rail_does_not_capture_wheel);
delegate_test!(compact_operator_rail_skips_focus_cycle => app::exact_test_compact_operator_rail_skips_focus_cycle);
delegate_test!(diff_renderer_uses_stacked_layout_in_narrow_geometries => tests::module_diff_renderer_uses_stacked_layout_in_narrow_geometries);
delegate_test!(wide_diff_renderer_pairs_before_and_after_columns => tests::module_wide_diff_renderer_pairs_before_and_after_columns);
delegate_test!(startup_slash_commands_execute_without_menu => app::exact_test_startup_slash_commands_execute_without_menu);
delegate_test!(slash_new_preserves_draft_and_returns_home => app::exact_test_slash_new_preserves_draft_and_returns_home);
delegate_test!(replay_mode_disables_slash_workflow => app::exact_test_replay_mode_disables_slash_workflow);
delegate_test!(slash_replay_opens_history_and_restores_draft => app::exact_test_slash_replay_opens_history_and_restores_draft);
delegate_test!(slash_resume_opens_history_and_restores_draft => app::exact_test_slash_resume_opens_history_and_restores_draft);
delegate_test!(slash_events_opens_review_surface => app::exact_test_slash_events_opens_review_surface);
delegate_test!(slash_status_opens_status_dialog_and_restores_draft => app::exact_test_slash_status_opens_status_dialog_and_restores_draft);
delegate_test!(status_dialog_mcp_rows_match_harness_states => ui::exact_test_status_dialog_mcp_rows_match_harness_states);
delegate_test!(status_dialog_render_snapshot_covers_harness_sections => ui::exact_test_status_dialog_render_snapshot_covers_harness_sections);
delegate_test!(status_dialog_formatters_section_disabled_when_none => ui::exact_test_status_dialog_formatters_section_disabled_when_none);
delegate_test!(status_dialog_formatters_section_lists_enabled_language => ui::exact_test_status_dialog_formatters_section_lists_enabled_language);
delegate_test!(slash_shell_closes_review_surface => app::exact_test_slash_shell_closes_review_surface);
delegate_test!(slash_follow_toggles_follow_mode => app::exact_test_slash_follow_toggles_follow_mode);
delegate_test!(live_slash_compact_appears_when_supported => app::exact_test_live_slash_compact_appears_when_supported);
delegate_test!(live_slash_compact_emits_ui_intent => app::exact_test_live_slash_compact_emits_ui_intent);
delegate_test!(auth_slash_and_palette_emit_ui_intent_mid_session => app::exact_test_auth_slash_and_palette_emit_ui_intent_mid_session);
delegate_test!(connect_slash_command_emits_open_auth_manager => app::exact_test_connect_slash_command_emits_open_auth_manager);
delegate_test!(connect_slash_command_passes_provider_args => app::exact_test_connect_slash_command_passes_provider_args);
delegate_test!(connect_slash_command_available_in_session => app::exact_test_connect_slash_command_available_in_session);
delegate_test!(no_provider_banner_shown_when_disconnected => app::exact_test_no_provider_banner_shown_when_disconnected);
delegate_test!(apply_auth_backend_result_updates_banner => app::exact_test_apply_auth_backend_result_updates_banner);
delegate_test!(apply_auth_backend_result_failure_shows_error => app::exact_test_apply_auth_backend_result_failure_shows_error);
delegate_test!(select_model_step_shows_models => app::exact_test_select_model_step_shows_models);
delegate_test!(select_model_skip_goes_to_success => app::exact_test_select_model_skip_goes_to_success);
delegate_test!(select_model_select_goes_to_success => app::exact_test_select_model_select_goes_to_success);
delegate_test!(toast_set_on_auth_success => app::exact_test_toast_set_on_auth_success);
delegate_test!(toast_set_on_auth_failure => app::exact_test_toast_set_on_auth_failure);
delegate_test!(any_key_closes_dialog_on_success => app::exact_test_any_key_closes_dialog_on_success);
delegate_test!(live_without_compact_support_hides_slash_compact => app::exact_test_live_without_compact_support_hides_slash_compact);
delegate_test!(slash_menu_lists_lineage_commands => app::exact_test_slash_menu_lists_lineage_commands);
delegate_test!(slash_lineage_write_commands_blocked_in_replay => app::exact_test_slash_lineage_write_commands_blocked_in_replay);
delegate_test!(slash_lineage_write_commands_blocked_when_live_unstable => app::exact_test_slash_lineage_write_commands_blocked_when_live_unstable);
delegate_test!(slash_lineage_descriptions_use_harness_branding => app::exact_test_slash_lineage_descriptions_use_harness_branding);
delegate_test!(revert_workspace_palette_availability => app::exact_test_revert_workspace_palette_availability);
delegate_test!(most_recent_workspace_snapshot_request_id => app::exact_test_most_recent_workspace_snapshot_request_id);
delegate_test!(request_workspace_revert_emits_intent => app::exact_test_request_workspace_revert_emits_intent);

mod shell_overlay_contract;
delegate_test!(startup_surface_renders_without_onboarding_overlay => shell_overlay_contract::startup_surface_renders_without_onboarding_overlay);
delegate_test!(replay_mode_never_reports_lifecycle_shell_actions => shell_overlay_contract::replay_mode_never_reports_lifecycle_shell_actions);
delegate_test!(permission_modal_preempts_palette_and_slash => shell_overlay_contract::permission_modal_preempts_palette_and_slash);
delegate_test!(completed_sessions_show_inline_completion_state_instead_of_handoff_card => shell_overlay_contract::completed_sessions_show_inline_completion_state_instead_of_handoff_card);
delegate_test!(live_shell_uses_single_chrome_path => shell_overlay_contract::live_shell_uses_single_chrome_path);
delegate_test!(live_shell_status_strip_has_single_priority_order => shell_overlay_contract::live_shell_status_strip_has_single_priority_order);

mod live_shell_state;
delegate_test!(live_shell_footer_is_shortcuts_only => live_shell_state::live_shell_footer_is_shortcuts_only);
delegate_test!(primary_and_wide_live_shells_hide_metadata_header => live_shell_state::primary_and_wide_live_shells_hide_metadata_header);
delegate_test!(completed_shell_bottom_rows_do_not_duplicate_command_help_footers => live_shell_state::completed_shell_bottom_rows_do_not_duplicate_command_help_footers);
delegate_test!(live_state_matrix_preserves_shell_structure => live_shell_state::live_state_matrix_preserves_shell_structure);

delegate_test!(legacy_live_redesign_gate_is_removed => shell_overlay_contract::legacy_live_redesign_gate_is_removed);

mod replay_command_history;
delegate_test!(replay_read_only_copy_matches_operator_shell_contract => replay_command_history::replay_read_only_copy_matches_operator_shell_contract);
delegate_test!(replay_shell_is_read_only_without_tab_bar => replay_command_history::replay_shell_is_read_only_without_tab_bar);
delegate_test!(command_palette_groups_commands_for_shell => replay_command_history::command_palette_groups_commands_for_shell);
delegate_test!(session_switcher_groups_entries_by_recency => replay_command_history::session_switcher_groups_entries_by_recency);
delegate_test!(session_history_overlay_sorts_results_deterministically => replay_command_history::session_history_overlay_sorts_results_deterministically);
delegate_test!(footer_shortcuts_collapse_without_overlap => replay_command_history::footer_shortcuts_collapse_without_overlap);
delegate_test!(slash_commands_only_track_leading_slash_input => replay_command_history::slash_commands_only_track_leading_slash_input);

mod startup_composer;
delegate_test!(startup_home_screen_renders_compose_first_shell => startup_composer::startup_home_screen_renders_compose_first_shell);
delegate_test!(startup_home_screen_uses_minimal_compat_shell => startup_composer::startup_home_screen_uses_minimal_compat_shell);
delegate_test!(startup_composer_keeps_inset_input_then_metadata_row_order => startup_composer::startup_composer_keeps_inset_input_then_metadata_row_order);
delegate_test!(startup_composer_width_stays_capped_for_shell => startup_composer::startup_composer_width_stays_capped_for_shell);
delegate_test!(dense_live_composer_uses_full_height_without_metadata_row => startup_composer::dense_live_composer_uses_full_height_without_metadata_row);
delegate_test!(dense_live_compaction_feedback_uses_toast_when_metadata_row_is_absent => startup_composer::dense_live_compaction_feedback_uses_toast_when_metadata_row_is_absent);
delegate_test!(live_composer_disclosure_keeps_compact_summary_and_commands => startup_composer::live_composer_disclosure_keeps_compact_summary_and_commands);

delegate_test!(slash_overlay_uses_reference_navigation_keys => shell_overlay_contract::slash_overlay_uses_reference_navigation_keys);
delegate_test!(slash_overlay_uses_input_width_aligned_rows_and_accent_selection => shell_overlay_contract::slash_overlay_uses_input_width_aligned_rows_and_accent_selection);

delegate_test!(new_session_preserves_unsent_draft_across_home_navigation => shell_overlay_contract::new_session_preserves_unsent_draft_across_home_navigation);
delegate_test!(command_driven_session_switch_emits_correct_ui_intent => shell_overlay_contract::command_driven_session_switch_emits_correct_ui_intent);

mod shell_geometry;
delegate_test!(live_shell_geometry_contract_is_rule_based => shell_geometry::live_shell_geometry_contract_is_rule_based);
delegate_test!(live_shell_threshold_edges_are_stable => shell_geometry::live_shell_threshold_edges_are_stable);
delegate_test!(dense_minimum_shell_hides_sidebar_and_caps_overlays => shell_geometry::dense_minimum_shell_hides_sidebar_and_caps_overlays);
delegate_test!(slash_overlay_matches_composer_text_input_width => shell_geometry::slash_overlay_matches_composer_text_input_width);
delegate_test!(live_shell_hidden_header_modes_remove_in_shell_anchor => shell_geometry::live_shell_hidden_header_modes_remove_in_shell_anchor);
delegate_test!(live_shell_minimum_modes_stay_headerless => shell_geometry::live_shell_minimum_modes_stay_headerless);
delegate_test!(live_shell_redesign_guardrails_preserve_primary_contract => shell_geometry::live_shell_redesign_guardrails_preserve_primary_contract);

delegate_test!(overlays_share_elevated_card_language => shell_overlay_contract::overlays_share_elevated_card_language);
delegate_test!(quiet_overlay_helper_rows_use_semantic_chrome_palette => shell_overlay_contract::quiet_overlay_helper_rows_use_semantic_chrome_palette);
delegate_test!(permission_modal_remains_visually_dominant_and_fail_closed => shell_overlay_contract::permission_modal_remains_visually_dominant_and_fail_closed);

delegate_test!(overlay_stack_orders_permission_above_commands_and_slash => app::AppState::exact_test_overlay_stack_orders_permission_above_commands_and_slash);

delegate_test!(live_shell_redesign_preserves_replay_overlay_and_permission_parity => shell_overlay_contract::live_shell_redesign_preserves_replay_overlay_and_permission_parity);

mod fixture_helpers;
mod render_helpers;
mod surface_contract_data;
mod theme_layout;
mod transcript_fixture_helpers;
pub(super) use fixture_helpers::*;
pub(super) use render_helpers::*;
use surface_contract_data::*;
pub(super) use transcript_fixture_helpers::*;
delegate_test!(harness_dark_theme_is_default => theme_layout::harness_dark_theme_is_default);
delegate_test!(theme_tokens_cover_live_shell_states => theme_layout::theme_tokens_cover_live_shell_states);
delegate_test!(harness_dark_theme_has_exact_palette => theme_layout::harness_dark_theme_has_exact_palette);
delegate_test!(command_palette_state_filters_existing_commands => theme_layout::command_palette_state_filters_existing_commands);
delegate_test!(hovered_wheel_target_uses_layout_plan => theme_layout::hovered_wheel_target_uses_layout_plan);
delegate_test!(layout_plan_minimum_geometry_matches_shell_contract => theme_layout::layout_plan_minimum_geometry_matches_shell_contract);
delegate_test!(layout_plan_primary_geometry_matches_shell_contract => theme_layout::layout_plan_primary_geometry_matches_shell_contract);
delegate_test!(layout_plan_primary_empty_operator_rail_keeps_fixed_width => theme_layout::layout_plan_primary_empty_operator_rail_keeps_fixed_width);
delegate_test!(layout_plan_split_empty_operator_rail_keeps_fixed_width => theme_layout::layout_plan_split_empty_operator_rail_keeps_fixed_width);
delegate_test!(wide_primary_live_layout_uses_available_width => theme_layout::wide_primary_live_layout_uses_available_width);
delegate_test!(split_window_live_layout_uses_available_width => theme_layout::split_window_live_layout_uses_available_width);
delegate_test!(live_layout_breakpoints_choose_shell_variant => theme_layout::live_layout_breakpoints_choose_shell_variant);
delegate_test!(layout_breakpoints_match_shell_parity_contract => theme_layout::layout_breakpoints_match_shell_parity_contract);

mod surface_contract;
delegate_test!(full_surface_scope_matrix_is_defined => surface_contract::full_surface_scope_matrix_is_defined);
delegate_test!(live_shell_noise_budget_contract_is_defined => surface_contract::live_shell_noise_budget_contract_is_defined);
delegate_test!(legacy_three_row_composer_contract_removed => surface_contract::legacy_three_row_composer_contract_removed);
delegate_test!(live_shell_composer_contract_matches_shell_parity => surface_contract::live_shell_composer_contract_matches_shell_parity);
delegate_test!(live_shell_composer_progressive_disclosure_by_width => surface_contract::live_shell_composer_progressive_disclosure_by_width);
delegate_test!(live_run_shell_places_under_input_controls_above_the_status_strip => surface_contract::live_run_shell_places_under_input_controls_above_the_status_strip);
delegate_test!(live_shell_composer_disabled_states_share_same_structure => surface_contract::live_shell_composer_disabled_states_share_same_structure);
delegate_test!(compact_geometry_uses_overlay_sidebar_and_minimal_footer => surface_contract::compact_geometry_uses_overlay_sidebar_and_minimal_footer);
delegate_test!(focus_order_cycles_transcript_sidebar_composer => surface_contract::focus_order_cycles_transcript_sidebar_composer);
delegate_test!(hovered_wheel_target_uses_sidebar_overlay_hit_areas => surface_contract::hovered_wheel_target_uses_sidebar_overlay_hit_areas);
delegate_test!(session_view_tracks_request_turn_and_tool_state => surface_contract::session_view_tracks_request_turn_and_tool_state);
delegate_test!(session_view_ignores_duplicate_seq_without_losing_ui_state => surface_contract::session_view_ignores_duplicate_seq_without_losing_ui_state);

#[cfg(test)]
#[path = "lib_tests/orchestration_projection_identity.rs"]
mod orchestration_projection_identity;
delegate_test!(orchestration_projection_resolves_owner_labels => orchestration_projection_identity::orchestration_projection_resolves_owner_labels);
delegate_test!(orchestration_projection_ignores_duplicate_seq_events => orchestration_projection_identity::orchestration_projection_ignores_duplicate_seq_events);
delegate_test!(orchestration_projection_preserves_background_notification_terminal_states => orchestration_projection_identity::orchestration_projection_preserves_background_notification_terminal_states);
delegate_test!(background_notification_projects_chat_reminder_without_duplicate_user_event => orchestration_projection_identity::background_notification_projects_chat_reminder_without_duplicate_user_event);
delegate_test!(operator_sidebar_shows_running_child_turn_before_task_tool_finishes => orchestration_projection_identity::operator_sidebar_shows_running_child_turn_before_task_tool_finishes);
#[cfg(test)]
#[path = "lib_tests/orchestration_projection_state.rs"]
mod orchestration_projection_state;
delegate_test!(orchestration_projection_tracks_queued_started_completed_counts => orchestration_projection_state::orchestration_projection_tracks_queued_started_completed_counts);
delegate_test!(orchestration_projection_tracks_stale_then_late_result => orchestration_projection_state::orchestration_projection_tracks_stale_then_late_result);
delegate_test!(orchestration_projection_distinguishes_background_failure_and_timeout => orchestration_projection_state::orchestration_projection_distinguishes_background_failure_and_timeout);
delegate_test!(orchestration_projection_retains_only_recent_terminal_rows => orchestration_projection_state::orchestration_projection_retains_only_recent_terminal_rows);

mod permission_runtime;
delegate_test!(permission_modal_snapshot_renders_request => permission_runtime::permission_modal_snapshot_renders_request);
delegate_test!(overlay_stack_orders_details_palette_permission => permission_runtime::overlay_stack_orders_details_palette_permission);
delegate_test!(permission_modal_preempts_palette => permission_runtime::permission_modal_preempts_palette);
delegate_test!(focus_returns_after_palette_close => permission_runtime::focus_returns_after_palette_close);
delegate_test!(live_status_strip_distinguishes_terminal_states => permission_runtime::live_status_strip_distinguishes_terminal_states);

mod transcript_flow;
delegate_test!(run_finished_keeps_transcript_and_ready_composer => transcript_flow::run_finished_keeps_transcript_and_ready_composer);
delegate_test!(streaming_transcript_auto_scrolls_to_latest_wrapped_content => transcript_flow::streaming_transcript_auto_scrolls_to_latest_wrapped_content);
delegate_test!(transcript_scrollbar_matches_session_shape => transcript_flow::transcript_scrollbar_matches_session_shape);
delegate_test!(transcript_page_down_reaches_response_tail_after_scrolling_up => transcript_flow::transcript_page_down_reaches_response_tail_after_scrolling_up);
delegate_test!(transcript_without_overflow_hides_scrollbar => transcript_flow::transcript_without_overflow_hides_scrollbar);
delegate_test!(disconnected_stream_disables_composer_with_reopen_guidance => transcript_flow::disconnected_stream_disables_composer_with_reopen_guidance);
delegate_test!(transcript_renders_inline_tool_states_and_prompt_echo => transcript_flow::transcript_renders_inline_tool_states_and_prompt_echo);
delegate_test!(transcript_tool_rows_keep_status_but_not_raw_json_dump => transcript_flow::transcript_tool_rows_keep_status_but_not_raw_json_dump);
delegate_test!(transcript_shell_renders_bubbleless_document_flow => transcript_flow::transcript_shell_renders_bubbleless_document_flow);
delegate_test!(transcript_shell_remains_scannable_without_bubble_cards => transcript_flow::transcript_shell_remains_scannable_without_bubble_cards);
delegate_test!(transcript_status_metadata_is_inline_not_chrome => transcript_flow::transcript_status_metadata_is_inline_not_chrome);
delegate_test!(transcript_turn_spacing_collapses_without_losing_actor_boundaries => transcript_flow::transcript_turn_spacing_collapses_without_losing_actor_boundaries);
delegate_test!(nested_transcript_rows_preserve_prefix_on_wrapped_continuations => transcript_flow::nested_transcript_rows_preserve_prefix_on_wrapped_continuations);
delegate_test!(thinking_visibility_toggle_hides_and_restores_inline_thinking_rows => transcript_flow::thinking_visibility_toggle_hides_and_restores_inline_thinking_rows);
delegate_test!(tool_details_toggle_collapses_successful_tool_payloads => transcript_flow::tool_details_toggle_collapses_successful_tool_payloads);
delegate_test!(failed_tool_rows_still_surface_error_summary => transcript_flow::failed_tool_rows_still_surface_error_summary);
delegate_test!(permission_overlay_preserves_draft_and_transcript_context => transcript_flow::permission_overlay_preserves_draft_and_transcript_context);
delegate_test!(permission_overlay_ignores_plain_draft_input_once_prompt_is_active => transcript_flow::permission_overlay_ignores_plain_draft_input_once_prompt_is_active);
delegate_test!(permission_overlay_preserves_existing_draft_without_buffering_new_letters => transcript_flow::permission_overlay_preserves_existing_draft_without_buffering_new_letters);

mod runtime_review_surface;
delegate_test!(runtime_state_overlay_is_quiet_and_actionable => runtime_review_surface::runtime_state_overlay_is_quiet_and_actionable);
delegate_test!(runtime_state_overlay_never_stacks_over_permission_modal => runtime_review_surface::runtime_state_overlay_never_stacks_over_permission_modal);
delegate_test!(degraded_and_disconnected_states_share_overlay_structure => runtime_review_surface::degraded_and_disconnected_states_share_overlay_structure);
delegate_test!(failure_overlay_is_specific_without_visual_noise => runtime_review_surface::failure_overlay_is_specific_without_visual_noise);
delegate_test!(details_drawer_toggles_without_leaving_live_surface => runtime_review_surface::details_drawer_toggles_without_leaving_live_surface);
delegate_test!(operator_sidebar_matches_parity_information_architecture => runtime_review_surface::operator_sidebar_matches_parity_information_architecture);
delegate_test!(operator_sidebar_uses_secondary_quiet_chrome => runtime_review_surface::operator_sidebar_uses_secondary_quiet_chrome);
delegate_test!(operator_sidebar_uses_explicit_empty_states => runtime_review_surface::operator_sidebar_uses_explicit_empty_states);
delegate_test!(operator_sidebar_recovery_section_surfaces_artifacts_and_navigation_hints => runtime_review_surface::operator_sidebar_recovery_section_surfaces_artifacts_and_navigation_hints);
delegate_test!(operator_sidebar_modified_files_include_diff_artifact_paths => runtime_review_surface::operator_sidebar_modified_files_include_diff_artifact_paths);
delegate_test!(operator_sidebar_preserves_section_order_and_copy => runtime_review_surface::operator_sidebar_preserves_section_order_and_copy);
delegate_test!(live_shell_no_longer_renders_debug_inspector_labels => runtime_review_surface::live_shell_no_longer_renders_debug_inspector_labels);
delegate_test!(review_surfaces_are_command_driven_without_tab_contract => runtime_review_surface::review_surfaces_are_command_driven_without_tab_contract);
delegate_test!(review_surfaces_restore_panel_chrome => runtime_review_surface::review_surfaces_restore_panel_chrome);

mod command_session_surface;
delegate_test!(session_shell_hides_tab_chrome_and_replay_review_is_command_driven => command_session_surface::session_shell_hides_tab_chrome_and_replay_review_is_command_driven);
delegate_test!(live_mode_accepts_input_without_focus_switch => command_session_surface::live_mode_accepts_input_without_focus_switch);
delegate_test!(command_palette_renders_and_filters => command_session_surface::command_palette_renders_and_filters);
delegate_test!(command_palette_exposes_model_switcher_when_models_are_configured => command_session_surface::command_palette_exposes_model_switcher_when_models_are_configured);
delegate_test!(command_palette_dims_background_instead_of_repainting_it => command_session_surface::command_palette_dims_background_instead_of_repainting_it);
delegate_test!(command_palette_empty_state_renders => command_session_surface::command_palette_empty_state_renders);
delegate_test!(command_palette_filtered_results_preserve_overlay_command_order => command_session_surface::command_palette_filtered_results_preserve_overlay_command_order);
delegate_test!(command_palette_includes_session_history_entry => command_session_surface::command_palette_includes_session_history_entry);
delegate_test!(session_history_picker_renders_resumable_and_replay_rows => command_session_surface::session_history_picker_renders_resumable_and_replay_rows);
delegate_test!(session_history_filter_matches_visible_fields_and_fuzzy_title => command_session_surface::session_history_filter_matches_visible_fields_and_fuzzy_title);
delegate_test!(continue_picker_filters_to_interactive_sessions => command_session_surface::continue_picker_filters_to_interactive_sessions);
delegate_test!(replay_picker_keeps_prompt_runs_visible => command_session_surface::replay_picker_keeps_prompt_runs_visible);
delegate_test!(focus_returns_after_session_history_close => command_session_surface::focus_returns_after_session_history_close);
delegate_test!(command_palette_enter_executes_selected_command => command_session_surface::command_palette_enter_executes_selected_command);
delegate_test!(palette_escape_preserves_prompt_draft => command_session_surface::palette_escape_preserves_prompt_draft);
delegate_test!(session_pin_toggles_and_sorts_pinned_first => command_session_surface::session_pin_toggles_and_sorts_pinned_first);
delegate_test!(session_delete_two_press_arms_then_emits_intent => command_session_surface::session_delete_two_press_arms_then_emits_intent);
delegate_test!(session_rename_dialog_opens_and_cancels => command_session_surface::session_rename_dialog_opens_and_cancels);
delegate_test!(theme_dialog_opens_and_cycles_themes => command_session_surface::theme_dialog_opens_and_cycles_themes);
delegate_test!(theme_dialog_escape_closes_without_applying => command_session_surface::theme_dialog_escape_closes_without_applying);
delegate_test!(model_favorite_toggles_and_sorts_first => command_session_surface::model_favorite_toggles_and_sorts_first);

mod startup_lifecycle_surface;
delegate_test!(startup_surface_renders_primary_actions => startup_lifecycle_surface::startup_surface_renders_primary_actions);
delegate_test!(startup_typing_moves_to_quick_start_prompt => startup_lifecycle_surface::startup_typing_moves_to_quick_start_prompt);
delegate_test!(startup_palette_remains_secondary_and_draft_safe => startup_lifecycle_surface::startup_palette_remains_secondary_and_draft_safe);
delegate_test!(post_run_handoff_renders_next_actions => startup_lifecycle_surface::post_run_handoff_renders_next_actions);
delegate_test!(post_run_failure_handoff_renders_recovery_actions => startup_lifecycle_surface::post_run_failure_handoff_renders_recovery_actions);
delegate_test!(post_run_handoff_disables_prompt_submission => startup_lifecycle_surface::post_run_handoff_disables_prompt_submission);
delegate_test!(double_escape_interrupts_active_live_turn_after_harness_confirmation => startup_lifecycle_surface::double_escape_interrupts_active_live_turn_after_harness_confirmation);
delegate_test!(interrupt_confirmation_is_scoped_to_current_active_turn_set => startup_lifecycle_surface::interrupt_confirmation_is_scoped_to_current_active_turn_set);
delegate_test!(continued_quiescent_bootstrap_shows_handoff_before_reopening_live_conversation => startup_lifecycle_surface::continued_quiescent_bootstrap_shows_handoff_before_reopening_live_conversation);
delegate_test!(lifecycle_shell_state_transitions => startup_lifecycle_surface::lifecycle_shell_state_transitions);
delegate_test!(lifecycle_shell_snapshots_preserve_startup_and_handoff_contracts => startup_lifecycle_surface::lifecycle_shell_snapshots_preserve_startup_and_handoff_contracts);
delegate_test!(session_history_browse_preserves_draft => startup_lifecycle_surface::session_history_browse_preserves_draft);
delegate_test!(new_session_resets_transcript_but_keeps_unsent_draft => startup_lifecycle_surface::new_session_resets_transcript_but_keeps_unsent_draft);

mod live_interaction_surface;
delegate_test!(permission_modal_preempts_prompt_submission => live_interaction_surface::permission_modal_preempts_prompt_submission);
delegate_test!(continue_disabled_session_shows_reason_banner => live_interaction_surface::continue_disabled_session_shows_reason_banner);
delegate_test!(replay_session_intent_never_enables_prompt_submission => live_interaction_surface::replay_session_intent_never_enables_prompt_submission);
delegate_test!(overlay_wheel_routing_preserved => live_interaction_surface::overlay_wheel_routing_preserved);
delegate_test!(replay_secondary_surfaces_remain_reachable_after_live_shell_refactor => live_interaction_surface::replay_secondary_surfaces_remain_reachable_after_live_shell_refactor);
delegate_test!(composer_enter_submits_and_shift_enter_inserts_newline => live_interaction_surface::composer_enter_submits_and_shift_enter_inserts_newline);
delegate_test!(composer_ctrl_j_inserts_newline => live_interaction_surface::composer_ctrl_j_inserts_newline);
delegate_test!(composer_submits_queued_followup_while_streaming => live_interaction_surface::composer_submits_queued_followup_while_streaming);
delegate_test!(session_shell_registry_only_exposes_home_and_session_shells => live_interaction_surface::session_shell_registry_only_exposes_home_and_session_shells);
delegate_test!(replay_mode_does_not_render_orchestration_summary => live_interaction_surface::replay_mode_does_not_render_orchestration_summary);

mod startup_live_empty_surface;
delegate_test!(startup_shell_shows_profile_provider_and_model_chrome => startup_live_empty_surface::startup_shell_shows_profile_provider_and_model_chrome);
delegate_test!(lifecycle_shell_narrow_layout_renders_primary_cta => startup_live_empty_surface::lifecycle_shell_narrow_layout_renders_primary_cta);
delegate_test!(startup_card_uses_lifecycle_geometry_contract => startup_live_empty_surface::startup_card_uses_lifecycle_geometry_contract);
delegate_test!(startup_card_moves_closer_to_dock_in_tall_and_split_windows => startup_live_empty_surface::startup_card_moves_closer_to_dock_in_tall_and_split_windows);
delegate_test!(live_empty_state_uses_shared_startup_copy_without_mode_badges => startup_live_empty_surface::live_empty_state_uses_shared_startup_copy_without_mode_badges);
delegate_test!(live_shell_minimum_geometry_snapshot_renders_without_overlap => startup_live_empty_surface::live_shell_minimum_geometry_snapshot_renders_without_overlap);
delegate_test!(live_shell_primary_geometry_snapshot_renders_without_overlap => startup_live_empty_surface::live_shell_primary_geometry_snapshot_renders_without_overlap);
delegate_test!(live_empty_state_snapshot_renders_input_first_shell => startup_live_empty_surface::live_empty_state_snapshot_renders_input_first_shell);
delegate_test!(live_empty_state_disappears_after_first_activity => startup_live_empty_surface::live_empty_state_disappears_after_first_activity);
delegate_test!(live_shell_orchestration_status_strip_snapshot => startup_live_empty_surface::live_shell_orchestration_status_strip_snapshot);
delegate_test!(live_status_strip_orchestration_summary_truncates_warning_last => startup_live_empty_surface::live_status_strip_orchestration_summary_truncates_warning_last);
delegate_test!(live_status_strip_renders_zero_state_orchestration_counts => startup_live_empty_surface::live_status_strip_renders_zero_state_orchestration_counts);
delegate_test!(live_empty_state_respects_compact_geometry => startup_live_empty_surface::live_empty_state_respects_compact_geometry);
delegate_test!(startup_home_matches_live_empty_shell_language => startup_live_empty_surface::startup_home_matches_live_empty_shell_language);
delegate_test!(live_empty_state_uses_shared_home_surface_tokens => startup_live_empty_surface::live_empty_state_uses_shared_home_surface_tokens);
delegate_test!(startup_and_live_empty_share_spacing_contract => startup_live_empty_surface::startup_and_live_empty_share_spacing_contract);

mod live_turn_surface;
delegate_test!(live_shell_type_first_input_snapshot => live_turn_surface::live_shell_type_first_input_snapshot);
delegate_test!(live_shell_shift_enter_keeps_draft_multiline => live_turn_surface::live_shell_shift_enter_keeps_draft_multiline);
delegate_test!(live_shell_enter_submits_and_echoes_prompt_snapshot => live_turn_surface::live_shell_enter_submits_and_echoes_prompt_snapshot);
delegate_test!(live_submitted_event_merges_duplicate_local_echo_before_rendering_response => live_turn_surface::live_submitted_event_merges_duplicate_local_echo_before_rendering_response);
delegate_test!(live_provider_request_id_alias_reuses_local_turn_placeholder => live_turn_surface::live_provider_request_id_alias_reuses_local_turn_placeholder);
delegate_test!(live_submitted_event_adopts_matching_local_echo_that_is_not_last => live_turn_surface::live_submitted_event_adopts_matching_local_echo_that_is_not_last);
delegate_test!(live_shell_inline_tool_state_snapshot => live_turn_surface::live_shell_inline_tool_state_snapshot);
delegate_test!(narrow_transcript_wrapped_top_level_turns_keep_alignment => live_turn_surface::narrow_transcript_wrapped_top_level_turns_keep_alignment);
delegate_test!(live_shell_permission_preserves_draft_snapshot => live_turn_surface::live_shell_permission_preserves_draft_snapshot);
delegate_test!(live_shell_degraded_bootstrap_snapshot => live_turn_surface::live_shell_degraded_bootstrap_snapshot);
delegate_test!(live_shell_disconnected_stream_snapshot => live_turn_surface::live_shell_disconnected_stream_snapshot);
delegate_test!(live_status_strip_suppresses_request_digest_banner_details => live_turn_surface::live_status_strip_suppresses_request_digest_banner_details);
delegate_test!(live_status_strip_suppresses_request_digest_from_cancelled_summary => live_turn_surface::live_status_strip_suppresses_request_digest_from_cancelled_summary);
delegate_test!(parent_view_ignores_streaming_child_activity_after_returning_from_subagent => live_turn_surface::parent_view_ignores_streaming_child_activity_after_returning_from_subagent);

mod orchestration_sidebar_surface;
delegate_test!(operator_sidebar_dedupes_running_task_tool_against_child_orchestration_row => orchestration_sidebar_surface::operator_sidebar_dedupes_running_task_tool_against_child_orchestration_row);
delegate_test!(live_shell_details_drawer_orchestration_snapshot => orchestration_sidebar_surface::live_shell_details_drawer_orchestration_snapshot);
delegate_test!(live_shell_details_drawer_orchestration_primary_snapshot => orchestration_sidebar_surface::live_shell_details_drawer_orchestration_primary_snapshot);
delegate_test!(live_shell_details_drawer_orchestration_overflow_snapshot => orchestration_sidebar_surface::live_shell_details_drawer_orchestration_overflow_snapshot);
delegate_test!(live_details_drawer_orchestration_warning_fallback => orchestration_sidebar_surface::live_details_drawer_orchestration_warning_fallback);
delegate_test!(layout_plan_primary_geometry_docks_live_details_sidebar => orchestration_sidebar_surface::layout_plan_primary_geometry_docks_live_details_sidebar);
delegate_test!(layout_plan_minimum_geometry_stacks_live_details_drawer => orchestration_sidebar_surface::layout_plan_minimum_geometry_stacks_live_details_drawer);
delegate_test!(live_session_shell_removes_tab_chrome_and_debug_drawer => orchestration_sidebar_surface::live_session_shell_removes_tab_chrome_and_debug_drawer);
delegate_test!(wide_shell_hides_header_when_sidebar_is_visible => orchestration_sidebar_surface::wide_shell_hides_header_when_sidebar_is_visible);
delegate_test!(replay_shell_uses_read_only_operator_layout => orchestration_sidebar_surface::replay_shell_uses_read_only_operator_layout);
delegate_test!(replay_read_only_composer_matches_quiet_contract => orchestration_sidebar_surface::replay_read_only_composer_matches_quiet_contract);
delegate_test!(replay_read_only_quiet_contract_survives_primary_compact_and_dense_geometries => orchestration_sidebar_surface::replay_read_only_quiet_contract_survives_primary_compact_and_dense_geometries);
delegate_test!(completed_shell_uses_disabled_quiet_composer => orchestration_sidebar_surface::completed_shell_uses_disabled_quiet_composer);
delegate_test!(replay_and_completed_states_preserve_read_only_and_session_preserved_copy => orchestration_sidebar_surface::replay_and_completed_states_preserve_read_only_and_session_preserved_copy);
