#[test]
fn provider_boundary_preserves_existing_message_shape() {
    let profile = boundary_profile();
    let request = AgentRequest {
        agent_id: "agent_1".to_string(),
        prompt: "Use a tool".to_string(),
        prompt_context: None,
        selected_file_tags: Vec::new(),
        selected_agent_tags: Vec::new(),
        selected_resource_tags: Vec::new(),
        model_ref: "mock:model-1".to_string(),
        model_settings: AgentModelSettings {
            variant: Some("gpt-5.4".to_string()),
            reasoning_effort: Some("high".to_string()),
            text_verbosity: Some("low".to_string()),
            reasoning_summary: Some("auto".to_string()),
        },
    };
    let prior_context = ProviderContext {
        compacted_summary: Some("Earlier work summary".to_string()),
        preserved_turns: vec![ProviderConversationTurn {
            user_prompt: "recent question".to_string(),
            assistant_response: "recent answer".to_string(),
            request_id: Some("req_prior".to_string()),
            first_seq: Some(7),
            last_seq: Some(9),
            artifacts: Vec::new(),
            ..ProviderConversationTurn::default()
        }],
        checkpoint: Some(checkpoint_metadata()),
    };
    let checkpoint = ProviderContextCheckpoint {
        metadata: checkpoint_metadata(),
        summary: "Earlier work summary".to_string(),
        recent_turns: prior_context.preserved_turns.clone(),
        pruned_tool_artifacts: Vec::new(),
        facts: ProviderCompactionFacts::default(),
        tail_boundary: None,
        summary_source: None,
        timeline_entry: None,
    };
    let projected_context = project_conversation(&[], &[(&checkpoint).into()])
        .expect("project checkpoint context")
        .messages
        .into_iter()
        .chain(std::iter::once(ConversationMessage::User(
            harness_core::conversation::ConversationUserMessage {
                request_id: request.agent_id.clone(),
                text: request.prompt.clone(),
                seq: None,
                agent_id: Some(request.agent_id.clone()),
            },
        )))
        .collect::<Vec<_>>();
    let tool_defs = build_provider_tool_defs(&profile, boundary_tool_registry().as_ref())
        .expect("build provider tool defs");

    let boundary = transform_context_for_provider(ProviderBoundaryInput {
        profile: &profile,
        model: AgentModelRef::parse(&request.model_ref),
        model_settings: request.model_settings.clone(),
        context: ProviderBoundaryContext::ProjectedHarness {
            messages: &projected_context,
            checkpoint: prior_context.checkpoint.as_ref(),
        },
        tools: Some(tool_defs.clone()),
        tool_choice: Some(ToolChoice::Auto),
    });

    let existing_messages =
        build_provider_context_messages(&profile, &prior_context, &request.provider_prompt());
    assert_eq!(boundary.messages, existing_messages);

    assert_eq!(
        boundary.messages[0],
        completion_message(MessageRole::System, "sys")
    );
    assert_eq!(boundary.messages[1].role, MessageRole::Assistant);
    assert!(boundary.messages[1]
        .content
        .contains("Checkpoint recap generated by the harness for older turns."));
    assert!(boundary.messages[1]
        .content
        .contains("Earlier work summary"));
    assert_eq!(
        boundary.messages[2],
        completion_message(MessageRole::User, "recent question")
    );
    assert_eq!(
        boundary.messages[3],
        completion_message(MessageRole::Assistant, "recent answer")
    );
    assert_eq!(
        boundary.messages[4],
        completion_message(MessageRole::User, "Use a tool")
    );

    assert_eq!(
        boundary.request,
        CompletionRequest {
            provider_id: Some("mock".to_string()),
            model_id: "model-1".to_string(),
            messages: existing_messages,
            temperature: Some(0.1),
            max_tokens: None,
            variant: Some("gpt-5.4".to_string()),
            reasoning_effort: Some("high".to_string()),
            text_verbosity: Some("low".to_string()),
            reasoning_summary: Some("auto".to_string()),
            tools: Some(tool_defs),
            tool_choice: Some(ToolChoice::Auto),
            context: Default::default(),
            stream: true,
        }
    );
}
#[test]
fn conversation_projection_failed_checkpoint_turn_status() {
    let checkpoint = ProviderContextCheckpoint {
        metadata: checkpoint_metadata(),
        summary: "Older work was compacted.".to_string(),
        recent_turns: vec![ProviderConversationTurn {
            user_prompt: "Try the risky operation".to_string(),
            assistant_response: "Partial answer before failure".to_string(),
            status: ProviderConversationTurnStatus::Failed,
            failure_stage: Some("provider_error".to_string()),
            failure_reason: Some("connection reset".to_string()),
            request_id: Some("req_failed".to_string()),
            first_seq: Some(7),
            last_seq: Some(9),
            artifacts: Vec::new(),
            messages: Vec::new(),
        }],
        pruned_tool_artifacts: Vec::new(),
        facts: ProviderCompactionFacts::default(),
        tail_boundary: None,
        summary_source: None,
        timeline_entry: None,
    };

    let projection =
        project_conversation(&[], &[(&checkpoint).into()]).expect("project failed checkpoint turn");

    let ConversationMessage::Assistant(assistant) = &projection.messages[2] else {
        panic!("expected checkpoint assistant message");
    };

    assert!(assistant
        .text
        .contains("Harness preserved an incomplete provider turn for continuity"));
    assert!(assistant.text.contains("Status: failed"));
    assert!(assistant.text.contains("Stage: provider_error"));
    assert!(assistant.text.contains("Reason: connection reset"));
    assert!(assistant.text.contains("Partial answer before failure"));
}
#[test]
fn conversation_projection_reconstructs_user_assistant_tool_messages_from_events() {
    let checkpoint = ProviderContextCheckpoint {
        metadata: ProviderContextCheckpointMetadata {
            checkpoint_id: "checkpoint_000002".to_string(),
            agent_id: "agent_000001".to_string(),
            run_id: "run_conversation_projection".to_string(),
            through_seq: 2,
            through_request_id: Some("req_000000".to_string()),
            provider_id: Some("default".to_string()),
            model_id: Some("gpt-5".to_string()),
            tokens_before: None,
            tokens_before_estimate: Some(128),
            tokens_after_estimate: Some(64),
            summary_tokens_estimate: Some(16),
            compacted_turns: Some(1),
            preserved_turns: Some(1),
            reduction_tokens_estimate: Some(64),
            reduction_percent_estimate: Some(50),
            trigger_reason: Some("manual".to_string()),
        },
        summary: "Older work was compacted.".to_string(),
        recent_turns: vec![ProviderConversationTurn {
            user_prompt: "Earlier question".to_string(),
            assistant_response: "Earlier answer".to_string(),
            request_id: Some("req_000000".to_string()),
            first_seq: Some(1),
            last_seq: Some(2),
            artifacts: Vec::new(),
            ..ProviderConversationTurn::default()
        }],
        pruned_tool_artifacts: Vec::new(),
        facts: ProviderCompactionFacts::default(),
        tail_boundary: None,
        summary_source: None,
        timeline_entry: None,
    };
    let checkpoints = vec![(&checkpoint).into()];

    let events = vec![
        envelope(
            1,
            EventActor::new(ActorKind::User, None),
            None,
            EventV1::UserMessageSubmitted(UserMessageSubmittedEvent {
                request_id: "req_000000".to_string(),
                text: "duplicate pre-checkpoint user".to_string(),
            }),
        ),
        envelope(
            2,
            worker(),
            Some("req_000000"),
            EventV1::ProviderStreamDelta(ProviderStreamDeltaEvent {
                request_id: "req_000000".to_string(),
                delta: "duplicate pre-checkpoint assistant".to_string(),
            }),
        ),
        envelope(
            3,
            EventActor::new(ActorKind::User, None),
            None,
            EventV1::UserMessageSubmitted(UserMessageSubmittedEvent {
                request_id: "req_000001".to_string(),
                text: "Inspect the project status.".to_string(),
            }),
        ),
        envelope(
            4,
            worker(),
            Some("req_000001"),
            EventV1::ProviderRequestStarted(ProviderRequestStartedEvent {
                request_id: "req_000001".to_string(),
                provider_id: "default".to_string(),
                model_id: "gpt-5".to_string(),
                prompt_summary: "Inspect the project status.".to_string(),
                request_digest: "digest-request".to_string(),
                metadata: None,
            }),
        ),
        envelope(
            5,
            worker(),
            Some("req_000001"),
            EventV1::ProviderStreamDelta(ProviderStreamDeltaEvent {
                request_id: "req_000001".to_string(),
                delta: "I'll ".to_string(),
            }),
        ),
        envelope(
            6,
            worker(),
            Some("req_000001"),
            EventV1::ProviderStreamDelta(ProviderStreamDeltaEvent {
                request_id: "req_000001".to_string(),
                delta: "check.".to_string(),
            }),
        ),
        envelope(
            7,
            worker(),
            Some("req_000001"),
            EventV1::ProviderRequestFinished(ProviderRequestFinishedEvent {
                request_id: "req_000001".to_string(),
                finish_reason: "tool_calls".to_string(),
                output_digest: Some("digest-output".to_string()),
                usage: None,
                metadata: None,
            }),
        ),
        envelope(
            8,
            worker(),
            Some("req_000001"),
            EventV1::ToolCallRequested(ToolCallRequestedEvent {
                tool_call_id: "toolcall_000001".to_string(),
                tool_id: "read".to_string(),
                args_summary: "{\"filePath\":\"README.md\"}".to_string(),
                args_digest: "digest-read-args".to_string(),
                metadata: None,
            }),
        ),
        envelope(
            9,
            worker(),
            Some("req_000001"),
            EventV1::ToolCallRequested(ToolCallRequestedEvent {
                tool_call_id: "toolcall_000002".to_string(),
                tool_id: "bash".to_string(),
                args_summary: "{\"command\":\"git status\"}".to_string(),
                args_digest: "digest-bash-args".to_string(),
                metadata: None,
            }),
        ),
        envelope(
            10,
            EventActor::new(ActorKind::System, Some("coordinator".to_string())),
            Some("req_000001"),
            EventV1::ToolCallFinished(ToolCallFinishedEvent {
                tool_call_id: "toolcall_000002".to_string(),
                status: ToolCallStatus::Succeeded,
                output_summary: Some("clean".to_string()),
                output_digest: Some("digest-bash-output".to_string()),
                output_json: None,
                metadata: None,
            }),
        ),
        envelope(
            11,
            EventActor::new(ActorKind::System, Some("coordinator".to_string())),
            Some("req_000001"),
            EventV1::ToolCallFinished(ToolCallFinishedEvent {
                tool_call_id: "toolcall_000001".to_string(),
                status: ToolCallStatus::Succeeded,
                output_summary: Some("README contents".to_string()),
                output_digest: Some("digest-read-output".to_string()),
                output_json: None,
                metadata: None,
            }),
        ),
    ];

    let projection = project_conversation(&events, &checkpoints).expect("project conversation");

    assert_eq!(projection.checkpoints.len(), 1);
    assert_eq!(projection.messages.len(), 7);

    let ConversationMessage::Checkpoint(summary) = &projection.messages[0] else {
        panic!("expected checkpoint summary message");
    };
    assert_eq!(summary.summary, "Older work was compacted.");

    let ConversationMessage::User(checkpoint_user) = &projection.messages[1] else {
        panic!("expected checkpoint user message");
    };
    assert_eq!(checkpoint_user.text, "Earlier question");

    let ConversationMessage::Assistant(checkpoint_assistant) = &projection.messages[2] else {
        panic!("expected checkpoint assistant message");
    };
    assert_eq!(checkpoint_assistant.text, "Earlier answer");

    let ConversationMessage::User(user) = &projection.messages[3] else {
        panic!("expected user message");
    };
    assert_eq!(user.request_id, "req_000001");
    assert_eq!(user.text, "Inspect the project status.");

    let ConversationMessage::Assistant(assistant) = &projection.messages[4] else {
        panic!("expected assistant message");
    };
    assert_eq!(assistant.text, "I'll check.");
    assert_eq!(assistant.stop_reason.as_deref(), Some("tool_calls"));
    assert_eq!(assistant.provider_id.as_deref(), Some("default"));
    assert_eq!(assistant.model_id.as_deref(), Some("gpt-5"));
    assert_eq!(assistant.tool_calls.len(), 2);
    assert_eq!(assistant.tool_calls[0].tool_call_id, "toolcall_000001");
    assert_eq!(assistant.tool_calls[0].tool_id, "read");
    assert_eq!(assistant.tool_calls[1].tool_call_id, "toolcall_000002");
    assert_eq!(assistant.tool_calls[1].tool_id, "bash");

    let ConversationMessage::ToolResult(first_result) = &projection.messages[5] else {
        panic!("expected first tool result message");
    };
    assert_eq!(first_result.tool_call_id, "toolcall_000001");
    assert_eq!(first_result.tool_id.as_deref(), Some("read"));
    assert_eq!(
        first_result.output_summary.as_deref(),
        Some("README contents")
    );

    let ConversationMessage::ToolResult(second_result) = &projection.messages[6] else {
        panic!("expected second tool result message");
    };
    assert_eq!(second_result.tool_call_id, "toolcall_000002");
    assert_eq!(second_result.tool_id.as_deref(), Some("bash"));
    assert_eq!(second_result.output_summary.as_deref(), Some("clean"));

    let provider_boundary = transform_context_for_provider(ProviderBoundaryInput {
        profile: &boundary_profile(),
        model: AgentModelRef::parse("mock:model-1"),
        model_settings: AgentModelSettings::default(),
        context: ProviderBoundaryContext::ProjectedHarness {
            messages: &projection.messages,
            checkpoint: None,
        },
        tools: None,
        tool_choice: None,
    });
    let assistant_message = provider_boundary
        .messages
        .iter()
        .find(|message| message.content == "I'll check.")
        .expect("assistant provider message");
    let assistant_tool_calls = assistant_message
        .assistant_tool_calls
        .as_ref()
        .expect("assistant tool calls should be provider-visible");
    assert_eq!(assistant_tool_calls[0].tool_call_id, "toolcall_000001");
    assert_eq!(assistant_tool_calls[0].function_name, "read");
    assert_eq!(
        assistant_tool_calls[0].arguments_json,
        r#"{"filePath":"README.md"}"#
    );
    let provider_tool_result = provider_boundary
        .messages
        .iter()
        .find(|message| {
            message.role == MessageRole::Tool
                && message.tool_call_id.as_deref() == Some("toolcall_000001")
        })
        .expect("tool result provider message");
    assert_eq!(provider_tool_result.name.as_deref(), Some("read"));
}
#[test]
fn provider_boundary_falls_back_for_non_json_historical_tool_args() {
    let events = vec![
        envelope(
            1,
            EventActor::new(ActorKind::User, None),
            Some("req_1"),
            EventV1::UserMessageSubmitted(UserMessageSubmittedEvent {
                request_id: "req_1".to_string(),
                text: "read a file".to_string(),
            }),
        ),
        envelope(
            2,
            worker(),
            Some("req_1"),
            EventV1::ProviderRequestStarted(ProviderRequestStartedEvent {
                request_id: "provider_req_1".to_string(),
                provider_id: "mock".to_string(),
                model_id: "model-1".to_string(),
                prompt_summary: "read a file".to_string(),
                request_digest: "digest".to_string(),
                metadata: None,
            }),
        ),
        envelope(
            3,
            worker(),
            Some("req_1"),
            EventV1::ToolCallRequested(ToolCallRequestedEvent {
                tool_call_id: "toolcall_1".to_string(),
                tool_id: "read".to_string(),
                args_summary: "read README.md…".to_string(),
                args_digest: "digest-args".to_string(),
                metadata: None,
            }),
        ),
    ];
    let projection = project_conversation(&events, &[]).expect("project conversation");

    let provider_boundary = transform_context_for_provider(ProviderBoundaryInput {
        profile: &boundary_profile(),
        model: AgentModelRef::parse("mock:model-1"),
        model_settings: AgentModelSettings::default(),
        context: ProviderBoundaryContext::ProjectedHarness {
            messages: &projection.messages,
            checkpoint: None,
        },
        tools: None,
        tool_choice: None,
    });

    let assistant_message = provider_boundary
        .messages
        .iter()
        .find(|message| message.role == MessageRole::Assistant)
        .expect("assistant message");
    let tool_calls = assistant_message
        .assistant_tool_calls
        .as_ref()
        .expect("tool calls");
    assert_eq!(tool_calls[0].arguments_json, "{}");
}
